"""The lens catalog as distro-check knows it: every lens group, every lens id and its severity.

A rule names a lens by id, and its severity is the lens's. The review
skills read the lens files; an installed checker has no lens files, so
it carries this table, and the set of lenses whose rule is `core`.
The platform's `tests/test_distro_check.py` holds both equal to its
`lenses/*.md` and its spec: a lens added, removed, re-rated, or
re-cited there is changed here in the same change.
"""

from __future__ import annotations

from acme.agentic_check.model import Severity

GROUPS: dict[str, str] = {
    "placement": "PLC",
    "workspaces": "WSP",
    "stations": "STN",
    "watch": "WAT",
    "intake": "INT",
    "evidence": "EVD",
    "wall": "WAL",
    "money": "MNY",
    "fleet": "FLT",
}
"""Each lens group and the id prefix of its lenses, in the order of the platform's `lenses/README.md`."""

LENSES: dict[str, Severity] = {
    "PLC-01": "medium",
    "PLC-02": "medium",
    "PLC-03": "high",
    "PLC-04": "high",
    "PLC-05": "medium",
    "PLC-06": "high",
    "PLC-07": "high",
    "PLC-08": "medium",
    "PLC-09": "medium",
    "PLC-10": "high",
    "PLC-11": "high",
    "PLC-12": "medium",
    "PLC-13": "high",
    "PLC-14": "high",
    "PLC-15": "high",
    "PLC-16": "high",
    "PLC-17": "medium",
    "PLC-18": "high",
    "PLC-19": "medium",
    "PLC-20": "high",
    "WSP-01": "medium",
    "WSP-02": "medium",
    "WSP-03": "high",
    "WSP-04": "high",
    "WSP-05": "high",
    "WSP-06": "high",
    "WSP-07": "high",
    "WSP-08": "high",
    "WSP-09": "high",
    "WSP-10": "high",
    "WSP-11": "high",
    "STN-01": "medium",
    "STN-02": "medium",
    "STN-03": "high",
    "STN-04": "high",
    "STN-05": "medium",
    "STN-06": "high",
    "STN-07": "high",
    "STN-08": "high",
    "STN-09": "high",
    "STN-10": "high",
    "STN-11": "high",
    "STN-12": "high",
    "WAT-01": "medium",
    "WAT-02": "medium",
    "WAT-03": "medium",
    "WAT-04": "high",
    "WAT-05": "medium",
    "WAT-06": "high",
    "WAT-07": "medium",
    "INT-01": "medium",
    "INT-02": "high",
    "INT-03": "medium",
    "INT-04": "high",
    "INT-05": "medium",
    "INT-06": "medium",
    "INT-07": "high",
    "INT-08": "high",
    "INT-09": "high",
    "INT-10": "high",
    "INT-11": "medium",
    "EVD-01": "high",
    "EVD-02": "high",
    "EVD-03": "high",
    "EVD-04": "high",
    "EVD-05": "high",
    "EVD-06": "high",
    "EVD-07": "high",
    "EVD-08": "high",
    "EVD-09": "high",
    "EVD-10": "high",
    "EVD-11": "medium",
    "EVD-12": "high",
    "EVD-13": "medium",
    "WAL-01": "high",
    "WAL-02": "high",
    "WAL-03": "high",
    "WAL-04": "high",
    "WAL-05": "high",
    "WAL-06": "high",
    "WAL-07": "high",
    "WAL-08": "high",
    "WAL-09": "medium",
    "WAL-10": "medium",
    "WAL-11": "medium",
    "WAL-12": "medium",
    "WAL-13": "medium",
    "MNY-01": "medium",
    "MNY-02": "medium",
    "MNY-03": "high",
    "MNY-04": "medium",
    "MNY-05": "high",
    "MNY-06": "high",
    "MNY-07": "medium",
    "MNY-08": "medium",
    "MNY-09": "medium",
    "MNY-10": "high",
    "MNY-11": "high",
    "MNY-12": "medium",
    "MNY-13": "high",
    "MNY-14": "high",
    "MNY-15": "medium",
    "MNY-16": "medium",
    "MNY-17": "medium",
    "MNY-18": "high",
    "FLT-01": "medium",
    "FLT-02": "medium",
    "FLT-03": "high",
    "FLT-04": "medium",
    "FLT-05": "medium",
    "FLT-06": "medium",
    "FLT-07": "medium",
    "FLT-08": "medium",
    "FLT-09": "high",
    "FLT-10": "high",
    "FLT-11": "medium",
    "FLT-12": "medium",
    "FLT-13": "medium",
}

CORE: frozenset[str] = frozenset(
    {
        "EVD-01",
        "EVD-02",
        "EVD-03",
        "EVD-04",
        "EVD-08",
        "EVD-09",
        "EVD-10",
        "INT-02",
        "MNY-10",
        "MNY-11",
        "PLC-03",
        "PLC-04",
        "PLC-05",
        "PLC-06",
        "PLC-07",
        "PLC-11",
        "PLC-12",
        "PLC-13",
        "PLC-14",
        "PLC-15",
        "PLC-16",
        "PLC-17",
        "STN-04",
        "STN-05",
        "STN-06",
        "STN-07",
        "STN-08",
        "STN-11",
        "STN-12",
        "WAL-01",
        "WAL-02",
        "WAL-03",
        "WAL-05",
        "WAL-06",
        "WSP-04",
        "WSP-05",
        "WSP-06",
        "WSP-07",
        "WSP-08",
    }
)
"""The lenses whose first Source, the section that states the rule, is tagged
`core` in the spec. A departure from such a rule is a different platform,
never a deviation, so no disable or exception may name one."""
