# generated by datamodel-codegen:
#   filename:  openapi.json

from datetime import timedelta
from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, SecretStr


class AccountDeletedView(BaseModel):
    """
    The account is gone: `deleted_at` is when. The database's backups
    still hold it until they expire, seven days on. `provider_logout_url` is
    where the browser goes next, as on a sign-out; null when the sign-in
    left no session there.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None


class AgentKind(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1, title='Agent Kind')]


class Title(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1, title='Title')]


class ActionKind(StrEnum):
    start_session = 'start_session'
    message_session = 'message_session'


class ActionView(BaseModel):
    agent_kind: Annotated[str | None, Field(title='Agent Kind')]
    brief: Annotated[str, Field(title='Brief')]
    kind: ActionKind
    project_id: Annotated[UUID | None, Field(title='Project Id')]
    session_id: Annotated[UUID | None, Field(title='Session Id')]
    title: Annotated[str | None, Field(title='Title')]


class Actor(StrEnum):
    """
    Who produced a step.
    """
    person = 'person'
    program = 'program'
    agent = 'agent'
    model = 'model'
    engine = 'engine'
    external = 'external'


class TtlDays(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=90, title='Ttl Days')]


class Capability(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9_.-]{0,62}$')]


class CostMicros(RootModel[int]):
    root: Annotated[int, Field(ge=0, title='Cost Micros')]


class Tokens(RootModel[int]):
    root: Annotated[int, Field(ge=0, title='Tokens')]


class AmountRequest(BaseModel):
    """
    A budget's new amount: reference cost in millionths, native tokens, or
    both. A unit left out is not bounded, and an amount bounds one at least.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    cost_micros: Annotated[CostMicros | None, Field(title='Cost Micros')] = None
    tokens: Annotated[Tokens | None, Field(title='Tokens')] = None


class Arm(StrEnum):
    candidate = 'candidate'
    baseline = 'baseline'


class ArmResultView(BaseModel):
    """
    One arm's result: its trials, how many passed, the mean of their
    scores, and the sum of their costs.
    """
    cost_micros: Annotated[int, Field(title='Cost Micros')]
    passed: Annotated[int, Field(title='Passed')]
    score: Annotated[float, Field(title='Score')]
    trials: Annotated[int, Field(title='Trials')]


class BudgetScopeKind(StrEnum):
    session = 'session'
    tree = 'tree'
    person = 'person'
    project = 'project'
    team = 'team'
    tenant = 'tenant'


class ClaimRequest(BaseModel):
    """
    The version of `exec` work the host reads, and nothing else: what it
    is handed is its identity's to say.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    exec_version: Annotated[int, Field(ge=1, title='Exec Version')]


class ClaimedWorkView(BaseModel):
    """
    One item a host was handed, under a lease, as `exec` work of
    `wire_version`. `payload` is the item's, as its kind fixes it.
    `org_id` is the tenant whose work it is, the host's own.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    id: Annotated[UUID, Field(title='Id')]
    kind: Annotated[str, Field(title='Kind')]
    lease_expires_at: Annotated[AwareDatetime | None, Field(title='Lease Expires At')]
    org_id: Annotated[UUID, Field(title='Org Id')]
    payload: Annotated[dict[str, Any], Field(title='Payload')]
    target_id: Annotated[UUID, Field(title='Target Id')]
    wire_version: Annotated[int, Field(title='Wire Version')]


class CommandPartView(BaseModel):
    seq: Annotated[int, Field(title='Seq')]
    stream: Annotated[str, Field(title='Stream')]
    text: Annotated[str, Field(title='Text')]


class ArgvItem(RootModel[str]):
    root: Annotated[str, Field(max_length=4096, min_length=1)]


class CommandRequest(BaseModel):
    """
    A command by hand: what it runs, where in the workspace, and how long
    it may take. Its key is the request's idempotency key.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: Annotated[list[ArgvItem], Field(max_length=256, min_length=1, title='Argv')]
    cwd: Annotated[str | None, Field(max_length=4096, min_length=1, title='Cwd')] = '.'
    timeout_seconds: Annotated[int | None, Field(gt=0, le=3600, title='Timeout Seconds')] = 300


class ConfirmTotpRequest(BaseModel):
    """
    The first code from the authenticator, which confirms the secret.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class ConnectInstallationRequest(BaseModel):
    """
    The grant the system handed the person who installed the platform:
    the integration reads the installation from it, never from the caller.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    grant: Annotated[str, Field(max_length=4096, min_length=1, title='Grant')]


class ContentState(StrEnum):
    """
    Where what a step says is. The state answers, so no caller compares
    strings.
    """
    plain = 'plain'
    sealed = 'sealed'
    absent = 'absent'


class ControlCommand(StrEnum):
    """
    What a `control` step records: a command that travels out of band.
    """
    pause = 'pause'
    resume = 'resume'
    cancel = 'cancel'
    interrupt = 'interrupt'
    compact = 'compact'
    approve = 'approve'
    deny = 'deny'
    unlock = 'unlock'


class ControlKind(StrEnum):
    """
    What one line of a host's control stream says.
    """
    wake = 'wake'
    ping = 'ping'
    cancel = 'cancel'
    interrupt = 'interrupt'
    deadline = 'deadline'
    revoke = 'revoke'


class RequestSeq(RootModel[int]):
    root: Annotated[int, Field(ge=1, title='Request Seq')]


class ControlView(BaseModel):
    """
    One line of a host's control stream. `wake` asks it to claim now,
    `ping` keeps the stream open, and the rest end the item named at once.
    """
    id: Annotated[UUID | None, Field(title='Id')] = None
    item_id: Annotated[UUID | None, Field(title='Item Id')] = None
    kind: ControlKind


class CreateOrgRequest(BaseModel):
    """
    An org with its owner, as `bootstrap` seeds one. The owner's identity
    is created with its personal org when the email is new; the owner signs
    in through the identity provider with the address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    owner_email: Annotated[str, Field(min_length=1, title='Owner Email')]
    owner_name: Annotated[str, Field(max_length=200, min_length=1, title='Owner Name')]
    slug: Annotated[str, Field(max_length=100, min_length=1, title='Slug')]


class Label(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,62}$')]


class CreatePoolRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    labels: Annotated[list[Label] | None, Field(max_length=32, title='Labels')] = None
    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]
    region: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,31}$', title='Region')]


class Slug(RootModel[str]):
    root: Annotated[str, Field(max_length=48, min_length=1, title='Slug')]


class CreateTeamOrgRequest(BaseModel):
    """
    A team org the caller makes and owns. `slug` is lower-case letters and
    digits joined by hyphens; left out, one is made from the name. A taken
    slug is 409.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    slug: Annotated[Slug | None, Field(title='Slug')] = None


class CredentialKind(StrEnum):
    api_key = 'api_key'
    session_token = 'session_token'
    login = 'login'
    socket_ticket = 'socket_ticket'
    operator_token = 'operator_token'
    internal = 'internal'


class CrossingKind(StrEnum):
    enrollment = 'enrollment'
    claim = 'claim'
    stream_part = 'stream_part'
    artifact = 'artifact'
    result = 'result'


class Decision(StrEnum):
    """
    From the least strict to the most.
    """
    allow = 'allow'
    approve = 'approve'
    deny = 'deny'


class DecisionRequest(BaseModel):
    """
    A person's decision on the tool call at a seq. A denial's note is what
    the model reads.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    approve: Annotated[bool, Field(title='Approve')]
    note: Annotated[str | None, Field(max_length=100000, title='Note')] = ''


class ReturnTo(RootModel[str]):
    root: Annotated[str, Field(max_length=2000, min_length=1, title='Return To')]


class DeleteAccountRequest(BaseModel):
    """
    The account's email as the person typed it, which is how they say
    they mean it; and, as on the sign-out, where the identity provider sends
    the browser once it has ended its own session.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=1, title='Email')]
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class DeleteOrgRequest(BaseModel):
    """
    The org's name as its owner typed it, which is how they say they mean
    it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]


class DeliveryReceivedView(BaseModel):
    """
    The delivery checked out and is queued; the provider stops retrying.
    """
    received: Annotated[bool, Field(title='Received')]


class DevSignInRequest(BaseModel):
    """
    Local and test only: a sign-in by address alone, with no browser round
    trip, for the seed, the traffic generator, and the tests. A
    person nobody knew is made, with their personal org. A deployed
    environment never serves it: the route answers 404 there, and the
    process refuses to start with it on.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str | None, Field(max_length=200, title='Display Name')] = ''
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]


class DeviceSignInView(BaseModel):
    """
    The start of a sign-in for a device with no browser, the command
    line. The person opens `verification_uri_complete` (or
    `verification_uri` and types `user_code`) in any browser; the device
    keeps `device_code` to itself and asks `POST /v1/auth/device/token`
    with it every `interval` seconds, for at most `expires_in` seconds.
    """
    device_code: Annotated[str, Field(title='Device Code')]
    expires_in: Annotated[int, Field(title='Expires In')]
    interval: Annotated[int, Field(title='Interval')]
    user_code: Annotated[str, Field(title='User Code')]
    verification_uri: Annotated[str, Field(title='Verification Uri')]
    verification_uri_complete: Annotated[str, Field(title='Verification Uri Complete')]


class DeviceTokenRequest(BaseModel):
    """
    The device code a device sign-in started with. The answer is a
    sign-in's once the person confirmed it; before that, 400
    `sign_in_pending` (or `sign_in_slow_down`: ask less often), and 401
    `sign_in_refused` when they declined or it expired.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    device_code: Annotated[str, Field(max_length=500, min_length=1, title='Device Code')]


class Effect(StrEnum):
    """
    What a repeat of a call may do.
    """
    read_only = 'read_only'
    idempotent = 'idempotent'
    unsafe = 'unsafe'


class Effort(StrEnum):
    """
    How hard a model works on a call. A provider that has no such level
    for a model leaves it out and names what it dropped.
    """
    none = 'none'
    low = 'low'
    medium = 'medium'
    high = 'high'
    xhigh = 'xhigh'
    max = 'max'


class Region(RootModel[str]):
    root: Annotated[str, Field(max_length=64, min_length=1, title='Region')]


class EligibilityBody(BaseModel):
    """
    What a fill offers: zero data retention, a region.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    region: Annotated[Region | None, Field(title='Region')] = None
    zero_retention: Annotated[bool | None, Field(title='Zero Retention')] = False


class EligibilityView(BaseModel):
    region: Annotated[str | None, Field(title='Region')]
    zero_retention: Annotated[bool, Field(title='Zero Retention')]


class EnrollmentTokenView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class EntryKind(StrEnum):
    hold = 'hold'
    settlement = 'settlement'
    charge = 'charge'
    credit = 'credit'
    grant = 'grant'
    raise_ = 'raise'
    approval = 'approval'


class EventView(BaseModel):
    """
    One record of the tenant's append-only stream, paged by `after_seq`.
    `kind` is "<namespace>.<entity>.<action>", or an audit kind; the payload
    stays inside, an event is a record and not a second read path.
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class ExchangeSessionRequest(BaseModel):
    """
    The org to enter. Presented with the sign-in credential, it opens the
    first session; presented with a session, it is a switch, and that session
    ends in the same write.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: Annotated[UUID, Field(title='Org Id')]


class ExecDetailView(BaseModel):
    """
    An item the host holds: the call, the workspace, and the operation.
    """
    call_id: Annotated[UUID, Field(title='Call Id')]
    deadline: Annotated[AwareDatetime, Field(title='Deadline')]
    effect: Annotated[str, Field(title='Effect')]
    epoch: Annotated[int | None, Field(title='Epoch')]
    item_id: Annotated[UUID, Field(title='Item Id')]
    location: Annotated[str, Field(title='Location')]
    org_id: Annotated[UUID, Field(title='Org Id')]
    request: Annotated[dict[str, Any], Field(title='Request')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    spec: Annotated[dict[str, Any], Field(title='Spec')]


class ExecLeaseView(BaseModel):
    lease_expires_at: Annotated[AwareDatetime, Field(title='Lease Expires At')]


class ExecState(StrEnum):
    queued = 'queued'
    running = 'running'
    done = 'done'
    interrupted = 'interrupted'


class FetchCredentialRequest(BaseModel):
    """
    A read-only credential of the project's repository, as source control
    takes it over HTTPS. It goes to the tenant's store and is never read
    back.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    password: Annotated[SecretStr, Field(max_length=4096, min_length=1, title='Password')]
    username: Annotated[str, Field(max_length=200, min_length=1, pattern='^[^:\\s]+$', title='Username')]


class FetchCredentialView(BaseModel):
    """
    That the project's repository has a fetch credential, and who gave it
    when. Never its value.
    """
    project_id: Annotated[UUID, Field(title='Project Id')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    updated_by: Annotated[UUID, Field(title='Updated By')]
    version: Annotated[int, Field(title='Version')]


class FilePurpose(StrEnum):
    """
    Which context a file came from. The purpose decides the bounds an
    upload is held to and what `subject_id` names. A product adds a purpose
    per kind of file it keeps, with its bounds (`media.rules.BOUNDS`).
    """
    upload = 'upload'


class FileStatus(StrEnum):
    pending = 'pending'
    stored = 'stored'


class FileView(BaseModel):
    """
    A file the tenant keeps: its name, type, and size, never its bytes and
    never where they live. `status` is `pending` until the upload is
    confirmed, then `stored`.
    """
    content_type: Annotated[str, Field(title='Content Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    extension: Annotated[str, Field(title='Extension')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]
    status: FileStatus
    subject_id: Annotated[UUID | None, Field(title='Subject Id')]


class SchemaName(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1, title='Schema Name')]


class ThinkingBudget(RootModel[int]):
    root: Annotated[int, Field(gt=0, title='Thinking Budget')]


class AuthorizationClass(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,63}$', title='Authorization Class')]


class Tool(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,63}$', title='Tool')]


class GateBody(BaseModel):
    """
    The calls a gate selects, by tool or by class, and what they need: a
    person's approval, or a denial. A gate never allows.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    authorization_class: Annotated[AuthorizationClass | None, Field(title='Authorization Class')] = None
    decision: Decision
    tool: Annotated[Tool | None, Field(title='Tool')] = None


class GateView(BaseModel):
    authorization_class: Annotated[str | None, Field(title='Authorization Class')]
    decision: Decision
    tool: Annotated[str | None, Field(title='Tool')]


class GiveBackRequest(BaseModel):
    """
    What the person did, as the agent reads it on resume.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    stop: Annotated[bool | None, Field(title='Stop')] = False
    summary: Annotated[str, Field(max_length=100000, min_length=1, title='Summary')]


class HandRunView(BaseModel):
    """
    A command by hand as recorded: the item that holds what ran, the
    person it is attributed to, and the writer epoch it runs under.
    """
    command_key: Annotated[UUID, Field(title='Command Key')]
    epoch: Annotated[int, Field(title='Epoch')]
    item_id: Annotated[UUID, Field(title='Item Id')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    state: ExecState
    user_id: Annotated[UUID, Field(title='User Id')]


class HostState(StrEnum):
    """
    A host as the platform's gauge counts it: the label is bounded, and a
    host's own view is an operator-plane read.
    """
    online = 'online'
    offline = 'offline'
    below_floor = 'below_floor'


class InstallationView(BaseModel):
    """
    An installation of the platform in a system, connected by the tenant:
    every delivery that names it reaches this tenant alone.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    installation: Annotated[str, Field(title='Installation')]
    integration: Annotated[str, Field(title='Integration')]


class InvitationState(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    revoked = 'revoked'


class IsolationMode(StrEnum):
    """
    The isolation levels a host can run a workspace at, strongest first.
    """
    vm = 'vm'
    container = 'container'
    directory = 'directory'


class IssuedDownloadView(BaseModel):
    """
    A link to the file's bytes that works until `expires_at`. A null `url`
    means the store cannot sign one: the bytes come from
    `GET /v1/media/files/{id}/content`.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    url: Annotated[str | None, Field(title='Url')]


class IssuedEnrollmentTokenView(BaseModel):
    """
    The token in the clear, once: it enrolls hosts into its pool until
    it expires or is revoked. It is minted on every call, so a retry mints
    another, and the one never read expires on its own.
    """
    enrollment: EnrollmentTokenView
    token: Annotated[str | None, Field(title='Token')]


class IssuedHostCredentialView(BaseModel):
    """
    The host's own credential in the clear, once, and the identity it
    carries. It lives an hour; the host rotates it before then.
    """
    credential_id: Annotated[UUID, Field(title='Credential Id')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    host_id: Annotated[UUID, Field(title='Host Id')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    token: Annotated[str | None, Field(title='Token')]


class IssuedTicketView(BaseModel):
    """
    Carries the freshly minted socket ticket in the clear, once; redeeming
    it opens the channel and re-checks the credential behind it.
    """
    expires_in_seconds: Annotated[int, Field(title='Expires In Seconds')]
    ticket: Annotated[str, Field(title='Ticket')]


class IssuedTotpSecretView(BaseModel):
    """
    A freshly minted TOTP secret, once, as the `otpauth://` URI an
    authenticator app reads. A replay carries none.
    """
    otpauth_uri: Annotated[str | None, Field(title='Otpauth Uri')]


class KeyStatus(StrEnum):
    live = 'live'
    rotated = 'rotated'
    refused = 'refused'


class KnowledgeRequest(BaseModel):
    """
    An entry: its title, the words that trigger it, all of which must
    appear in what a session is about, and what it says. A trigger word
    with none of a-z, 0-9, `_`, `.` or `-` is refused: recall reads nothing
    in it, so it would match every session.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Annotated[str, Field(max_length=10000, min_length=1, title='Text')]
    title: Annotated[str, Field(max_length=200, min_length=1, title='Title')]
    trigger: Annotated[list[str], Field(max_length=20, min_length=1, title='Trigger')]


class KnowledgeStatus(StrEnum):
    suggested = 'suggested'
    reviewed = 'reviewed'
    rejected = 'rejected'


class KnowledgeView(BaseModel):
    """
    An entry, its state, who suggested and who reviewed it, and the
    version an edit names in `If-Match`.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    id: Annotated[UUID, Field(title='Id')]
    reviewed_by: Annotated[UUID | None, Field(title='Reviewed By')]
    status: KnowledgeStatus
    suggested_by: Annotated[UUID | None, Field(title='Suggested By')]
    text: Annotated[str, Field(title='Text')]
    title: Annotated[str, Field(title='Title')]
    trigger: Annotated[list[str], Field(title='Trigger')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    version: Annotated[int, Field(title='Version')]


class LedgerEntryView(BaseModel):
    """
    One entry, written once. A field a kind does not carry is null:

    - `hold`: `session_id`, `units` (the worst case, null when no price
      applies), and `cost_micros` (the exposure).
    - `settlement`: `hold_id`, `cost_micros` and `tokens` (what it spent).
    - `charge`: `hold_id`, `units`, and `amount_micros` (what the money
      buckets paid).
    - `credit`: `amount_micros` and `reference` (the payment's).
    - `grant`: `units`, `reason`, and `by` (the operator).
    - `raise`: `budget_id`, `cost_micros`, `tokens`, and `by`.
    - `approval`: `session_id`, `amount_micros` (the cost it allows), and
      `by`.
    """
    amount_micros: Annotated[int | None, Field(title='Amount Micros')] = None
    budget_id: Annotated[UUID | None, Field(title='Budget Id')] = None
    by: Annotated[UUID | None, Field(title='By')] = None
    cost_micros: Annotated[int | None, Field(title='Cost Micros')] = None
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    hold_id: Annotated[UUID | None, Field(title='Hold Id')] = None
    id: Annotated[UUID, Field(title='Id')]
    kind: EntryKind
    reason: Annotated[str | None, Field(title='Reason')] = None
    reference: Annotated[str | None, Field(title='Reference')] = None
    session_id: Annotated[UUID | None, Field(title='Session Id')] = None
    tokens: Annotated[int | None, Field(title='Tokens')] = None
    units: Annotated[int | None, Field(title='Units')] = None


class LedgerPageView(BaseModel):
    """
    One read of a tenant's ledger, the newest first. `has_more` says the
    read was cut at its limit and older entries match it too: narrow it by
    kind, hold, or session to reach them.
    """
    has_more: Annotated[bool, Field(title='Has More')]
    items: Annotated[list[LedgerEntryView], Field(title='Items')]


class LimitsBody(BaseModel):
    """
    The most its runs spend in a period, in millionths at list price, and
    the share one run may take; the most firings a period; the most runs at
    work at once; whether a stopped firing waits, and how many may; and the
    longest chain of automations a firing extends.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int, Field(gt=0, title='Concurrency')]
    cost_cap_micros: Annotated[int, Field(gt=0, title='Cost Cap Micros')]
    hop_limit: Annotated[int | None, Field(ge=1, title='Hop Limit')] = 3
    period: Annotated[timedelta | None, Field(title='Period')] = None
    queue: Annotated[bool | None, Field(title='Queue')] = False
    queue_depth: Annotated[int | None, Field(ge=1, title='Queue Depth')] = 50
    rate: Annotated[int, Field(gt=0, title='Rate')]
    run_cap_micros: Annotated[int, Field(gt=0, title='Run Cap Micros')]


class LimitsView(BaseModel):
    concurrency: Annotated[int, Field(title='Concurrency')]
    cost_cap_micros: Annotated[int, Field(title='Cost Cap Micros')]
    hop_limit: Annotated[int, Field(title='Hop Limit')]
    period: Annotated[timedelta, Field(title='Period')]
    queue: Annotated[bool, Field(title='Queue')]
    queue_depth: Annotated[int, Field(title='Queue Depth')]
    rate: Annotated[int, Field(title='Rate')]
    run_cap_micros: Annotated[int, Field(title='Run Cap Micros')]


class LiveReadView(BaseModel):
    """
    A handle to one session's open streams until `expires_at`. Read it
    at `GET /v1/live?handle=`; a viewer asks for a new one when it ends.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    handle: Annotated[str, Field(title='Handle')]
    session_id: Annotated[UUID, Field(title='Session Id')]


class LogoutRequest(BaseModel):
    """
    Where the identity provider sends the browser once it has ended its own
    session: this environment's portal page for it, and nothing else. Left
    out, the provider sends it to its default sign-out address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class LoopOutcome(StrEnum):
    """
    The five ways a loop ends. A park is none of them.
    """
    succeeded = 'succeeded'
    failed = 'failed'
    inconclusive = 'inconclusive'
    cancelled = 'cancelled'
    errored = 'errored'


class Environment(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,31}$', title='Environment')]


class Kind(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1, title='Kind')]


class PlanTier(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,31}$', title='Plan Tier')]


class Role1(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,63}$', title='Role')]


class Workload(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,31}$', title='Workload')]


class MatrixKeyBody(BaseModel):
    """
    What a row answers: each key it names must equal the question's, and a
    key left out matches every value. The row that names none matches every
    question.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    environment: Annotated[Environment | None, Field(title='Environment')] = None
    kind: Annotated[Kind | None, Field(title='Kind')] = None
    plan_tier: Annotated[PlanTier | None, Field(title='Plan Tier')] = None
    role: Annotated[Role1 | None, Field(title='Role')] = None
    workload: Annotated[Workload | None, Field(title='Workload')] = None


class MatrixKeyView(BaseModel):
    environment: Annotated[str | None, Field(title='Environment')]
    kind: Annotated[str | None, Field(title='Kind')]
    plan_tier: Annotated[str | None, Field(title='Plan Tier')]
    role: Annotated[str | None, Field(title='Role')]
    workload: Annotated[str | None, Field(title='Workload')]


class MatrixStatus(StrEnum):
    pending = 'pending'
    published = 'published'


class MessageRequest(BaseModel):
    """
    A message to the session, said in the caller's name. It wakes an idle
    session, and a running loop reads it at its next model request.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Annotated[str, Field(max_length=100000, min_length=1, title='Text')]


class ExpiresIn(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=3600, title='Expires In')]


class OperatorEventView(BaseModel):
    """
    The same record as an operator reads it, with the two provenance fields
    a tenant's own feed leaves out: the request that produced it and the app
    it came from, which is what a support investigation correlates on.
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    app: Annotated[str, Field(title='App')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    request_id: Annotated[UUID, Field(title='Request Id')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class OperatorRole(StrEnum):
    """
    What an allowlist entry lets an operator do across every tenant. Write
    includes read; the tenancy namespace's table says which permissions each
    role holds, as it does for `Role`.
    """
    read = 'read'
    write = 'write'


class OperatorTokenView(BaseModel):
    """
    One operator token as its operator reads it: never the secret, which is
    kept as its digest. `revoked_at` is set once it was ended.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class OperatorView(BaseModel):
    """
    Who the operator plane admitted: the identity and what its allowlist
    entry grants, so a skill checks it holds the entry it expects before it
    reads anything.
    """
    email: Annotated[str, Field(title='Email')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]
    operator_role: OperatorRole


class OrgKind(StrEnum):
    """
    What an org is for. Every person has exactly one personal org, made
    with them; every other org is a team org, made on purpose.
    """
    personal = 'personal'
    team = 'team'


class OrgView(BaseModel):
    """
    `kind` says what the org is for: every person has one `personal` org,
    made with them, which is never deleted and never changes hands; every
    other org is a `team` org.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')] = None
    id: Annotated[UUID, Field(title='Id')]
    kind: OrgKind
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class Origin(StrEnum):
    """
    Where a step came in.
    """
    portal = 'portal'
    cli = 'cli'
    api = 'api'
    integration = 'integration'
    automation = 'automation'
    parent = 'parent'
    engine = 'engine'


class OutputShape(StrEnum):
    text = 'text'
    schema = 'schema'


class OutputStream(StrEnum):
    stdout = 'stdout'
    stderr = 'stderr'


class OwnedOrgRef(BaseModel):
    """
    An org named in a refusal: enough to find it and to say which.
    """
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class ParkReason(StrEnum):
    """
    Why a loop waits, and so what clears it.
    """
    person = 'person'
    provider = 'provider'
    budget = 'budget'
    resource = 'resource'
    job = 'job'
    children = 'children'
    handover = 'handover'
    pause = 'pause'


class ParkView(BaseModel):
    """
    Why a parked loop waits, what clears it, and when it tries again by
    itself; a park only a person clears has no time.
    """
    reason: ParkReason
    retry_at: Annotated[AwareDatetime | None, Field(title='Retry At')]
    unlock: Annotated[str, Field(title='Unlock')]


class PartKind(StrEnum):
    text = 'text'
    thinking = 'thinking'
    tool_input = 'tool_input'
    tool_output = 'tool_output'


class Permission(StrEnum):
    read = 'read'
    write = 'write'
    manage_members = 'manage_members'
    manage_keys = 'manage_keys'


class PlaceSessionRequest(BaseModel):
    """
    One of the tenant's pools, or None for the cloud.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    pool_id: Annotated[UUID | None, Field(title='Pool Id')]


class PlatformSizeView(BaseModel):
    """
    How big the platform is, what the first responder to an alarm reads
    before it escalates: live tenants and users, and the events produced in
    the twenty-four hours from `since` to `counted_at`. The maintenance
    worker counts it every few minutes, and this is its latest count:
    `counted_at` says how old the answer is.
    """
    counted_at: Annotated[AwareDatetime, Field(title='Counted At')]
    events_last_24h: Annotated[int, Field(title='Events Last 24H')]
    since: Annotated[AwareDatetime, Field(title='Since')]
    tenants: Annotated[int, Field(title='Tenants')]
    users: Annotated[int, Field(title='Users')]


class PlaybookView(BaseModel):
    body: Annotated[str, Field(title='Body')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    description: Annotated[str, Field(title='Description')]
    gates: Annotated[list[GateView], Field(title='Gates')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    published_by: Annotated[UUID, Field(title='Published By')]
    version: Annotated[int, Field(title='Version')]


class TargetKind(RootModel[str]):
    root: Annotated[str, Field(max_length=64, min_length=1, title='Target Kind')]


class PolicyRuleBody(BaseModel):
    """
    What a rule matches and what it decides. A selector left unset matches
    any call; every target attribute it names must equal the target's.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    authorization_class: Annotated[AuthorizationClass | None, Field(title='Authorization Class')] = None
    decision: Decision
    effect: Effect | None = None
    target: Annotated[dict[str, str | int | bool] | None, Field(max_length=20, title='Target')] = None
    target_kind: Annotated[TargetKind | None, Field(title='Target Kind')] = None
    tool: Annotated[Tool | None, Field(title='Tool')] = None


class PolicyRuleView(BaseModel):
    authorization_class: Annotated[str | None, Field(title='Authorization Class')]
    decision: Decision
    effect: Effect | None
    target: Annotated[dict[str, Any], Field(title='Target')]
    target_kind: Annotated[str | None, Field(title='Target Kind')]
    tool: Annotated[str | None, Field(title='Tool')]


class PoolView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    labels: Annotated[list[str], Field(title='Labels')]
    name: Annotated[str, Field(title='Name')]
    region: Annotated[str, Field(title='Region')]


class Location(RootModel[str]):
    root: Annotated[str, Field(max_length=1024, min_length=1, title='Location')]


class Refused(RootModel[str]):
    root: Annotated[str, Field(max_length=2000, min_length=1, title='Refused')]


class PrepareRequest(BaseModel):
    """
    A host's answer to a prepare it claimed: where on it the workspace it
    made is, or why it made none. Exactly one of the two.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    location: Annotated[Location | None, Field(title='Location')] = None
    refused: Annotated[Refused | None, Field(title='Refused')] = None


class PreparedView(BaseModel):
    """
    Whether the session's workspace is now the one this host made. When
    it is not, another host of the pool holds it, and this host lets its
    own go.
    """
    held: Annotated[bool, Field(title='Held')]


class Provenance(StrEnum):
    """
    From the strongest to the weakest.
    """
    real = 'real'
    twin = 'twin'
    double = 'double'
    unavailable = 'unavailable'


class ProviderName(StrEnum):
    anthropic = 'anthropic'
    openai = 'openai'


class PublishRequest(BaseModel):
    """
    The next version of a playbook's name: its description, its body, and
    its gates.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    body: Annotated[str, Field(max_length=50000, min_length=1, title='Body')]
    description: Annotated[str, Field(max_length=1024, min_length=1, title='Description')]
    gates: Annotated[list[GateBody] | None, Field(max_length=50, title='Gates')] = None
    name: Annotated[str, Field(max_length=64, min_length=1, pattern='^[a-z0-9]+(-[a-z0-9]+)*$', title='Name')]


class PurposeUsageView(BaseModel):
    count: Annotated[int, Field(title='Count')]
    pending_count: Annotated[int, Field(title='Pending Count')]
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]


class RenameProjectRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]


class RepositoryBody(BaseModel):
    """
    A repository by its host's domain and its path there, such as
    `github.com` and `octo/reports`. Both are compared without case.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    host: Annotated[str, Field(max_length=253, pattern='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$', title='Host')]
    path: Annotated[str, Field(max_length=255, pattern='^[a-z0-9_][a-z0-9_.-]*(/[a-z0-9_][a-z0-9_.-]*)+$', title='Path')]


class RepositoryView(BaseModel):
    host: Annotated[str, Field(title='Host')]
    path: Annotated[str, Field(title='Path')]


class RetireRequest(BaseModel):
    """
    A model its provider retired, by name, as a fill names it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    model: Annotated[str, Field(max_length=200, min_length=1, title='Model')]
    provider: ProviderName


class RetirementView(BaseModel):
    """
    A retired model: no session resolves to it again, and a version that
    names it is not published. Recorded once a model.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    id: Annotated[UUID, Field(title='Id')]
    model: Annotated[str, Field(title='Model')]
    provider: ProviderName
    recorded_by: Annotated[UUID, Field(title='Recorded By')]


class ReviewRequest(BaseModel):
    """
    Keep a suggestion, so any session may recall it, or reject it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    keep: Annotated[bool, Field(title='Keep')]


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'
    viewer = 'viewer'
    service = 'service'


class RunsAs(StrEnum):
    """
    Whose authority an automation's action runs on.
    """
    creator = 'creator'
    automation_principal = 'automation_principal'


class SaveKeyRequest(BaseModel):
    """
    A key's value. It is written once, under a new reference, and no
    response, log, or error ever carries it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[SecretStr, Field(max_length=4096, min_length=1, title='Value')]


class SecondFactorRequest(BaseModel):
    """
    The code from an authenticator, presented with a sign-in credential.
    The answer is a new sign-in that records the verified code, which the
    operator plane asks of an enrolled operator. A code used once is
    refused.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class SessionControl(StrEnum):
    """
    The controls a person sends a session out of band. A decision on one
    tool call is a route of its own.
    """
    pause = 'pause'
    resume = 'resume'
    cancel = 'cancel'
    interrupt = 'interrupt'
    compact = 'compact'
    unlock = 'unlock'


class SessionStatus(StrEnum):
    pending = 'pending'
    running = 'running'
    parked = 'parked'
    idle = 'idle'


class SessionView(BaseModel):
    """
    Only the hash of a token is ever kept, so a session view carries no secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class SetShareRequest(BaseModel):
    """
    A tenant's fair share: the plan tier whose lane its loops run in,
    whether they run in a lane of their own instead, and how many of them
    run at once.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int, Field(ge=1, le=10000, title='Concurrency')]
    own_lane: Annotated[bool | None, Field(title='Own Lane')] = False
    plan_tier: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,31}$', title='Plan Tier')]


class ShareView(BaseModel):
    """
    A tenant's fair share as the operator wrote it, at its version.
    """
    concurrency: Annotated[int, Field(title='Concurrency')]
    org_id: Annotated[UUID, Field(title='Org Id')]
    own_lane: Annotated[bool, Field(title='Own Lane')]
    plan_tier: Annotated[str, Field(title='Plan Tier')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    updated_by: Annotated[UUID, Field(title='Updated By')]
    version: Annotated[int, Field(title='Version')]


class InvitationToken(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Invitation Token')]


class SignInCallbackRequest(BaseModel):
    """
    The code the browser brought back to the callback, and the verifier
    the sign-in's start answered with, which the API exchanges with the
    identity provider, server-side. The answer is a
    sign-in's (`IssuedLoginView`); a person nobody knew is signed up by it,
    with their personal org.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=500, min_length=1, title='Code')]
    code_verifier: Annotated[str, Field(max_length=128, min_length=43, title='Code Verifier')]
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None


class SignInStartRequest(BaseModel):
    """
    The start of a sign-in at the identity provider. `redirect_uri` is where
    the browser comes back with a code: this environment's portal callback,
    and nothing else. `state` is the caller's own random value, kept by the
    tab that started the sign-in and compared when the browser comes back,
    which binds the round trip to that tab; it may carry nothing else.
    `invitation_token` is the one an invitation's link carried, and
    `sign_up` opens the provider on its sign-up screen.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None
    redirect_uri: Annotated[str, Field(max_length=2000, min_length=1, title='Redirect Uri')]
    sign_up: Annotated[bool | None, Field(title='Sign Up')] = False
    state: Annotated[str, Field(max_length=200, min_length=16, title='State')]


class SignInStartView(BaseModel):
    """
    Where the browser goes next, the identity provider's sign-in, and the
    PKCE verifier the tab keeps beside its state and sends back with the
    code. The provider holds only the verifier's digest, so a code is worth
    nothing to anyone who does not hold it.
    """
    authorization_url: Annotated[str, Field(title='Authorization Url')]
    code_verifier: Annotated[str, Field(title='Code Verifier')]


class SignedOutView(BaseModel):
    """
    The credential that ended, a session, a sign-in, or an operator
    token, and `provider_logout_url`: where the browser goes next to end the
    identity provider's session behind it, so the next sign-in on this
    browser asks who it is. Null when the sign-in left no session there
    (the device sign-in, the local sign-in, an operator token). It names the
    provider's session, which is not a secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class Intent(StrEnum):
    sso = 'sso'
    domain_verification = 'domain_verification'


class SsoLinkRequest(BaseModel):
    """
    What the identity provider's admin portal opens on: the single sign-on
    connection (`sso`) or the org's domains (`domain_verification`), and the
    page of this environment's portal it links back to.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    intent: Annotated[Intent, Field(title='Intent')]
    return_url: Annotated[str, Field(max_length=2000, min_length=1, title='Return Url')]


class SsoLinkView(BaseModel):
    """
    A short-lived link to the admin portal; open it at once.
    """
    url: Annotated[str, Field(title='Url')]


class Role2(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,63}$')]


class StartSessionRequest(BaseModel):
    """
    A session to start on the latest version of a kind the product runs,
    in a project of the caller's tenant. Outside a local stack a session
    starts in a project or not at all.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Annotated[str, Field(max_length=200, min_length=1, title='Kind')]
    project_id: Annotated[UUID | None, Field(title='Project Id')] = None
    title: Annotated[str, Field(max_length=200, min_length=1, title='Title')]


class StartUploadRequest(BaseModel):
    """
    An upload to start: the file's name as the uploader had it, its type,
    and its size in bytes. The type must be one the purpose accepts and match
    the name's extension; the size is the most the store will take.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    content_type: Annotated[str, Field(max_length=255, min_length=1, title='Content Type')]
    name: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    size_bytes: Annotated[int, Field(gt=0, title='Size Bytes')]


class StepType(StrEnum):
    """
    What a step records. The type answers questions, so no caller
    compares strings.
    """
    message = 'message'
    event = 'event'
    control = 'control'
    model_request = 'model_request'
    model_response = 'model_response'
    tool_request = 'tool_request'
    tool_response = 'tool_response'
    summary = 'summary'
    parked = 'parked'
    resumed = 'resumed'
    loop_ended = 'loop_ended'
    switched = 'switched'
    environment_changed = 'environment_changed'


class StopKind(StrEnum):
    """
    What the control stream tells a host about one item it holds. Each
    ends the command at once.
    """
    cancel = 'cancel'
    interrupt = 'interrupt'
    deadline = 'deadline'
    revoke = 'revoke'


class StopReason(StrEnum):
    """
    Why a response stopped. A model's refusal is a response its agent kind
    handles, never a provider error.
    """
    end_turn = 'end_turn'
    tool_use = 'tool_use'
    output_limit = 'output_limit'
    refusal = 'refusal'
    content_filter = 'content_filter'
    pause = 'pause'


class StorageUsageView(BaseModel):
    """
    What the org keeps in the store, counted from its files: the stored ones
    per purpose and in total, and the uploads started and not yet confirmed.
    A removed file stops counting at once.
    """
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purposes: Annotated[list[PurposeUsageView], Field(title='Purposes')]
    total_count: Annotated[int, Field(title='Total Count')]
    total_size_bytes: Annotated[int, Field(title='Total Size Bytes')]


class StreamTruncatedDetail(BaseModel):
    """
    What a `stream_truncated` refusal carries: the floor, the highest seq
    trimmed from the stream, and the head. A client drops its cursor, reads
    afresh what it shows, and goes on from the head.
    """
    floor: Annotated[int, Field(title='Floor')]
    head: Annotated[int, Field(title='Head')]


class ToolFailure(StrEnum):
    """
    The class of a tool failure, decided where the failure happens. The
    model reads it with advice on what to do next.
    """
    invalid_input = 'invalid_input'
    transient = 'transient'
    timeout = 'timeout'
    denied = 'denied'
    interrupted = 'interrupted'
    permanent = 'permanent'


class TotpConfirmedView(BaseModel):
    """
    The second factor is enrolled: from now on the operator plane admits
    this identity only on a sign-in that verified a code, so the next
    request signs in again with one.
    """
    confirmed_at: Annotated[AwareDatetime, Field(title='Confirmed At')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]


class TrialView(BaseModel):
    """
    One trial: its arm, its session, where and when it ran, its cost, and
    what its acceptance verdict found.
    """
    arm: Arm
    broken: Annotated[list[str], Field(title='Broken')]
    cost_micros: Annotated[int, Field(title='Cost Micros')]
    executor: Annotated[str, Field(title='Executor')]
    passed: Annotated[bool, Field(title='Passed')]
    score: Annotated[float, Field(title='Score')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    started_at: Annotated[AwareDatetime, Field(title='Started At')]
    verdict_id: Annotated[UUID, Field(title='Verdict Id')]


class TriggerKind(StrEnum):
    event = 'event'
    schedule = 'schedule'


class TriggerView(BaseModel):
    arrivals: Annotated[list[str], Field(title='Arrivals')]
    effects: Annotated[list[str], Field(title='Effects')]
    every: Annotated[timedelta | None, Field(title='Every')]
    integrations: Annotated[list[str], Field(title='Integrations')]
    kind: TriggerKind


class UpdateIdentityRequest(BaseModel):
    """
    Where the person is, as an IANA name ("Europe/Istanbul"): the portal
    sends the browser's own on sign-in, and a time shown or sent to the
    person is in it; with none sent, in UTC. A name that is not one is
    422.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    time_zone: Annotated[str, Field(max_length=64, min_length=1, title='Time Zone')]


class UpdateMeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]


class UpdateMembershipRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Role


class UploadFieldView(BaseModel):
    name: Annotated[str, Field(title='Name')]
    value: Annotated[str, Field(title='Value')]


class UserView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    display_name: Annotated[str, Field(title='Display Name')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class WindowKind(StrEnum):
    life = 'life'
    hour = 'hour'
    day = 'day'
    week = 'week'
    month = 'month'
    span = 'span'


class WorkKind(StrEnum):
    NOOP = 'NOOP'
    ORCHESTRATION = 'ORCHESTRATION'
    WAKE_PARKED = 'WAKE_PARKED'
    DELETE_ACCOUNT = 'DELETE_ACCOUNT'
    DELETE_ORG = 'DELETE_ORG'
    WAKE_SESSION = 'WAKE_SESSION'
    WAKE_SESSIONS = 'WAKE_SESSIONS'
    LOOP = 'LOOP'
    VALIDATION = 'VALIDATION'
    EXEC = 'EXEC'
    WORKSPACE = 'WORKSPACE'


class WorkStatus(StrEnum):
    queued = 'queued'
    claimed = 'claimed'
    done = 'done'
    failed = 'failed'


class ActionBody(BaseModel):
    """
    Start a session of `agent_kind` titled `title` in the tenant's project
    `project_id`, or send the brief to the standing session `session_id`.
    The brief is the creator's word.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_kind: Annotated[AgentKind | None, Field(title='Agent Kind')] = None
    brief: Annotated[str, Field(max_length=20000, min_length=1, title='Brief')]
    kind: ActionKind
    project_id: Annotated[UUID | None, Field(title='Project Id')] = None
    session_id: Annotated[UUID | None, Field(title='Session Id')] = None
    title: Annotated[Title | None, Field(title='Title')] = None


class AddApiKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    role: Role
    ttl_days: Annotated[TtlDays | None, Field(title='Ttl Days')] = None


class AddMemberRequest(BaseModel):
    """
    A person in the org, as `add-member` seeds one; the owner and the
    service role are refused, since the one owner is the one the create
    minted.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]
    email: Annotated[str, Field(min_length=1, title='Email')]
    role: Role


class AdvertisementBody(BaseModel):
    """
    What a host probed at its startup, and nothing it did not.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: Annotated[list[Capability] | None, Field(max_length=64, title='Capabilities')] = None
    isolation_modes: Annotated[list[IsolationMode] | None, Field(max_length=3, title='Isolation Modes')] = None
    os: Annotated[str, Field(max_length=64, min_length=1, title='Os')]
    shell: Annotated[str | None, Field(max_length=64, title='Shell')] = ''


class AdvertisementView(BaseModel):
    capabilities: Annotated[list[str], Field(title='Capabilities')]
    isolation_modes: Annotated[list[IsolationMode], Field(title='Isolation Modes')]
    os: Annotated[str, Field(title='Os')]
    shell: Annotated[str, Field(title='Shell')]


class AgentSessionView(BaseModel):
    """
    A session: its kind, its title, and its status, which follows its
    steps. `pending` while an input waits for a run, `running` while a run
    holds its loop, `parked` while the loop waits, `idle` when no loop is
    open.
    """
    archived_at: Annotated[AwareDatetime | None, Field(title='Archived At')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    kind: Annotated[str, Field(title='Kind')]
    kind_version: Annotated[int, Field(title='Kind Version')]
    park: ParkView | None
    status: SessionStatus
    title: Annotated[str, Field(title='Title')]


class ApiKeyView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    role: Role
    user_id: Annotated[UUID, Field(title='User Id')]


class ApproverRuleBody(BaseModel):
    """
    Who may approve a call of one class: people's roles, never a service.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    authorization_class: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,63}$', title='Authorization Class')]
    roles: Annotated[list[Role], Field(max_length=5, min_length=1, title='Roles')]


class ApproverRuleView(BaseModel):
    authorization_class: Annotated[str, Field(title='Authorization Class')]
    roles: Annotated[list[Role], Field(title='Roles')]


class AutomationPrincipalView(BaseModel):
    """
    The tenant's automation principal: its id, the role it holds, and who
    granted it.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    granted_by: Annotated[UUID, Field(title='Granted By')]
    id: Annotated[UUID, Field(title='Id')]
    role: Role


class AutomationView(BaseModel):
    """
    An automation, whom it runs as, and who made and last edited it.
    """
    action: ActionView
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    enabled: Annotated[bool, Field(title='Enabled')]
    id: Annotated[UUID, Field(title='Id')]
    limits: LimitsView
    name: Annotated[str, Field(title='Name')]
    own_events: Annotated[bool, Field(title='Own Events')]
    runs_as: RunsAs
    trigger: TriggerView
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    updated_by: Annotated[UUID, Field(title='Updated By')]


class BenchmarkResultRequest(BaseModel):
    """
    What a benchmark run showed of a model for a model role: whether it
    passed, and where its evidence is (`run`, such as the run's id or its
    report's address). The latest result for the model and the role decides
    whether a version that serves the role with the model may be
    published.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    benchmark: Annotated[str, Field(pattern='^[a-z][a-z0-9_.-]{0,99}$', title='Benchmark')]
    model: Annotated[str, Field(max_length=200, min_length=1, title='Model')]
    passed: Annotated[bool, Field(title='Passed')]
    provider: ProviderName
    role: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,63}$', title='Role')]
    run: Annotated[str, Field(max_length=500, min_length=1, title='Run')]


class BenchmarkResultView(BaseModel):
    """
    A recorded result, written once.
    """
    benchmark: Annotated[str, Field(title='Benchmark')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    id: Annotated[UUID, Field(title='Id')]
    model: Annotated[str, Field(title='Model')]
    passed: Annotated[bool, Field(title='Passed')]
    provider: ProviderName
    recorded_by: Annotated[UUID, Field(title='Recorded By')]
    role: Annotated[str, Field(title='Role')]
    run: Annotated[str, Field(title='Run')]


class BudgetView(BaseModel):
    """
    A budget: its scope, its window, its amount, and the version a change
    of the amount names in `If-Match`.
    """
    cost_micros: Annotated[int | None, Field(title='Cost Micros')]
    id: Annotated[UUID, Field(title='Id')]
    scope_key: Annotated[str, Field(title='Scope Key')]
    scope_kind: BudgetScopeKind
    tokens: Annotated[int | None, Field(title='Tokens')]
    version: Annotated[int, Field(title='Version')]
    window_kind: WindowKind
    window_seconds: Annotated[int | None, Field(title='Window Seconds')]


class ClaimView(BaseModel):
    """
    What a claim answers: the item, or none when nothing is ready.
    """
    item: ClaimedWorkView | None


class CommandProgressView(BaseModel):
    """
    How a command stands: its state, its output after the last part read,
    and how it ended once it has. `refused` names why its host or the relay
    refused it, such as a command a later run fenced.
    """
    exit_code: Annotated[int | None, Field(title='Exit Code')] = None
    parts: Annotated[list[CommandPartView], Field(title='Parts')]
    refused: Annotated[str | None, Field(title='Refused')] = None
    state: ExecState
    stderr: Annotated[str | None, Field(title='Stderr')] = None
    stdout: Annotated[str | None, Field(title='Stdout')] = None
    stopped: StopKind | None = None
    timed_out: Annotated[bool | None, Field(title='Timed Out')] = False
    truncated: Annotated[bool | None, Field(title='Truncated')] = False


class ControlRequest(BaseModel):
    """
    A control. An interrupt names the seq of the tool request it stops,
    and no other control names one.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    command: SessionControl
    request_seq: Annotated[RequestSeq | None, Field(title='Request Seq')] = None


class CreateProjectRequest(BaseModel):
    """
    A project and the one repository it binds, which never moves.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    repository: RepositoryBody


class CrossingBody(BaseModel):
    """
    What the sender declares of the bytes it sends: what they are, their
    SHA-256 in hex, and their size.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: CrossingKind
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$', title='Sha256')]
    size: Annotated[int, Field(ge=0, title='Size')]


class EnrollRequest(BaseModel):
    """
    A host's name and its report, beside its enrollment token. The pool
    is the token's.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    advertisement: AdvertisementBody
    exec_version: Annotated[int, Field(ge=1, title='Exec Version')]
    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]


class FilePageView(BaseModel):
    """
    One page of the org's stored files, oldest first. `next_cursor` fetches
    the next page and is null on the last one.
    """
    items: Annotated[list[FileView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class FillBody(BaseModel):
    """
    A fill: a provider's model, how hard it works, its output bound and
    shape, its context window, and what it offers. The output bound fits
    inside the window, and a schema is named exactly when the output is one.
    An output left out is text, and an eligibility left out offers
    nothing.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    context_window: Annotated[int, Field(gt=0, title='Context Window')]
    effort: Effort | None = None
    eligibility: EligibilityBody | None = None
    max_output_tokens: Annotated[int, Field(gt=0, title='Max Output Tokens')]
    model: Annotated[str, Field(max_length=200, min_length=1, title='Model')]
    output: OutputShape | None = None
    provider: ProviderName
    schema_name: Annotated[SchemaName | None, Field(title='Schema Name')] = None
    thinking_budget: Annotated[ThinkingBudget | None, Field(title='Thinking Budget')] = None


class FillView(BaseModel):
    context_window: Annotated[int, Field(title='Context Window')]
    effort: Effort | None
    eligibility: EligibilityView
    max_output_tokens: Annotated[int, Field(title='Max Output Tokens')]
    model: Annotated[str, Field(title='Model')]
    output: OutputShape
    provider: ProviderName
    schema_name: Annotated[str | None, Field(title='Schema Name')]
    thinking_budget: Annotated[int | None, Field(title='Thinking Budget')]


class GrantRequest(BaseModel):
    """
    The role the automation principal holds: never above the granter's.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Role


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HeartbeatRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    advertisement: AdvertisementBody
    exec_version: Annotated[int, Field(ge=1, title='Exec Version')]


class HostView(BaseModel):
    """
    A host as its owner reads it: online while it called within the
    window and reads a version of `exec` work the platform still hands.
    """
    advertisement: AdvertisementView
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    exec_version: Annotated[int, Field(title='Exec Version')]
    id: Annotated[UUID, Field(title='Id')]
    last_seen_at: Annotated[AwareDatetime, Field(title='Last Seen At')]
    name: Annotated[str, Field(title='Name')]
    online: Annotated[bool, Field(title='Online')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class IdentityView(BaseModel):
    """
    The person behind the caller's user. `operator_role` is the allowlist
    entry: null for a person who is not an operator.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]
    operator_role: OperatorRole | None
    time_zone: Annotated[str | None, Field(title='Time Zone')] = None


class InvitationView(BaseModel):
    """
    A person asked to join the org. The identity provider sent the email
    with the link; `expires_at` is when the link stops working, after which
    the invitation is sent again or replaced.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    email: Annotated[str, Field(title='Email')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    state: InvitationState


class InviteMemberRequest(BaseModel):
    """
    The address to invite and the role the person gets, at most the
    caller's own.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]
    role: Role


class IssuedApiKeyView(BaseModel):
    """
    The key in the clear is present on the first response only: the stored
    outcome of the create carries no secret, so a replay under the same
    Idempotency-Key answers with `key` null and `Idempotent-Replayed: true`. A
    client that lost the first response revokes the key and issues another.
    """
    api_key: ApiKeyView
    key: Annotated[str | None, Field(title='Key')]


class IssuedOperatorTokenView(BaseModel):
    """
    The token in the clear, on this answer only; `id` names it afterwards,
    in the list and the revoke, and is no secret. The mint ends the sign-in
    it was given, so a client that lost this answer signs in again for
    another token and revokes the lost one by its id from the list.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    token: Annotated[str | None, Field(title='Token')]


class IssuedSessionView(BaseModel):
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    org: OrgView
    role: Role
    token: Annotated[str, Field(title='Token')]
    user: UserView


class IssuedUploadView(BaseModel):
    """
    A form to post the file with, straight to the store: every field, in
    order, then the file as the last field, named `file`. The signed policy
    holds the post to the file's type and at most its size, until
    `expires_at`. A null `url` means the store cannot take a post: the bytes
    go to `PUT /v1/media/files/{id}/content` instead. Then the upload is
    confirmed.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    fields: Annotated[list[UploadFieldView], Field(title='Fields')]
    url: Annotated[str | None, Field(title='Url')]


class LaneLoadView(BaseModel):
    kind: WorkKind
    lane: Annotated[str, Field(title='Lane')]
    ready: Annotated[int, Field(title='Ready')]


class LastOwnerDetail(BaseModel):
    """
    What a `last_owner` refusal carries: every team org the person is the
    last owner of, which they hand on or delete before their account goes.
    """
    orgs: Annotated[list[OwnedOrgRef], Field(title='Orgs')]


class LivePartView(BaseModel):
    """
    One part of a stream: its kind, its places, and its text. A part may
    join a run of one block's parts: it holds the places from `n` to
    `last`, and a reader resumes after `last`. `index` is the block of a
    model response it belongs to; a tool call's input names the call, and a
    tool's output its channel.
    """
    channel: Annotated[str | None, Field(title='Channel')] = None
    index: Annotated[int | None, Field(title='Index')] = None
    kind: PartKind
    last: Annotated[int, Field(title='Last')]
    n: Annotated[int, Field(title='N')]
    text: Annotated[str, Field(title='Text')]
    tool: Annotated[str | None, Field(title='Tool')] = None
    tool_use_id: Annotated[str | None, Field(title='Tool Use Id')] = None


class LiveStreamView(BaseModel):
    """
    One open stream: the step it adds up to, the oldest part the service
    still holds, the parts after the last one read, and whether parts never
    read were let go. The step holds them once it is stored.
    """
    dropped: Annotated[bool, Field(title='Dropped')]
    first: Annotated[int, Field(title='First')]
    parts: Annotated[list[LivePartView], Field(title='Parts')]
    step_id: Annotated[UUID, Field(title='Step Id')]


class LoopStandingView(BaseModel):
    """
    The session's loop item made last, and its place in line:
    `ready_ahead` items of any tenant are ready before it on its lane, and
    `running_ahead` of its tenant's loops run ahead of it, which the claim
    counts against the share.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    available_at: Annotated[AwareDatetime, Field(title='Available At')]
    claimed_by: Annotated[str | None, Field(title='Claimed By')]
    item_id: Annotated[UUID, Field(title='Item Id')]
    lane: Annotated[str, Field(title='Lane')]
    lease_expires_at: Annotated[AwareDatetime | None, Field(title='Lease Expires At')]
    max_attempts: Annotated[int, Field(title='Max Attempts')]
    ready_ahead: Annotated[int, Field(title='Ready Ahead')]
    running_ahead: Annotated[int, Field(title='Running Ahead')]
    status: WorkStatus


class MatrixRowBody(BaseModel):
    """
    A row: the questions it matches, and its fills, the first the fill and
    the rest the fallbacks, each named once. A row that names no match
    matches every question.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    fills: Annotated[list[FillBody], Field(max_length=8, min_length=1, title='Fills')]
    matches: MatrixKeyBody | None = None


class MatrixRowView(BaseModel):
    """
    A row: the questions it matches, the row's key, and its fills.
    """
    fills: Annotated[list[FillView], Field(title='Fills')]
    matches: MatrixKeyView


class MatrixVersionView(BaseModel):
    """
    A version: pending until an operator publishes it, and the matrix from
    then until the next is published. Its rows never change.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    number: Annotated[int, Field(title='Number')]
    published_at: Annotated[AwareDatetime | None, Field(title='Published At')]
    published_by: Annotated[UUID | None, Field(title='Published By')]
    roles: Annotated[list[str], Field(title='Roles')]
    rows: Annotated[list[MatrixRowView], Field(title='Rows')]
    status: MatrixStatus


class MeView(BaseModel):
    app: Annotated[str, Field(title='App')]
    org: OrgView
    permissions: Annotated[list[Permission], Field(title='Permissions')]
    role: Role
    user: UserView


class MembershipChoiceView(BaseModel):
    org: OrgView
    role: Role
    user: UserView


class MembershipView(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    teams: Annotated[list[UUID], Field(title='Teams')]
    user_id: Annotated[UUID, Field(title='User Id')]


class MintOperatorTokenRequest(BaseModel):
    """
    One permission, never wider than the caller's entry (`write` implies
    `read`), and a lifetime of at most an hour, an hour when absent.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: Annotated[ExpiresIn | None, Field(title='Expires In')] = None
    permission: OperatorRole


class NotificationView(BaseModel):
    """
    What waits on the caller: the session, why it parked, the one action
    that clears it, and that action's route, empty when none serves it yet.
    `read_at` is when the caller marked it read.
    """
    action: Annotated[str, Field(title='Action')]
    channel: Annotated[str, Field(title='Channel')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    id: Annotated[UUID, Field(title='Id')]
    link: Annotated[str, Field(title='Link')]
    provenance: Provenance | None
    read_at: Annotated[AwareDatetime | None, Field(title='Read At')]
    reason: ParkReason
    session_id: Annotated[UUID, Field(title='Session Id')]
    text: Annotated[str, Field(title='Text')]
    unlock: Annotated[str, Field(title='Unlock')]


class OperatorTokenPageView(BaseModel):
    """
    One page of the caller's live operator tokens, newest first;
    `next_cursor` as on `UserPageView`.
    """
    items: Annotated[list[OperatorTokenView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class OperatorWorkItemView(BaseModel):
    """
    One background job as an operator reads it: what it does and for
    which record, where it stands, and how many of its attempts are spent.
    The payload and the claim stay the worker's.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    available_at: Annotated[AwareDatetime, Field(title='Available At')]
    id: Annotated[UUID, Field(title='Id')]
    kind: WorkKind
    last_error: Annotated[str | None, Field(title='Last Error')]
    max_attempts: Annotated[int, Field(title='Max Attempts')]
    status: WorkStatus
    target_id: Annotated[UUID, Field(title='Target Id')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class OrgDeletedView(BaseModel):
    """
    The org is gone for everyone in it: `deleted_at` is when. `session` is
    the owner's new session in their personal org, which replaces the one
    that asked, as a switch's does; null when none could be made, and the
    owner signs in again.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    session: IssuedSessionView | None = None


class OrgPageView(BaseModel):
    """
    One page of every org, by id, for the operator plane; `next_cursor` as
    on `UserPageView`.
    """
    items: Annotated[list[OrgView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class PartRequest(BaseModel):
    """
    One part of an item's output, in the order the host read it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    crossing: CrossingBody
    data: Annotated[str, Field(max_length=90000, title='Data')]
    seq: Annotated[int, Field(ge=0, title='Seq')]
    stream: OutputStream


class PlacementView(BaseModel):
    """
    Where a session runs. A pinned session with no host of its pool
    online is `waiting`; it never moves to the cloud by itself.
    """
    hosts_online: Annotated[int, Field(title='Hosts Online')]
    pool: PoolView | None
    session_id: Annotated[UUID, Field(title='Session Id')]
    version: Annotated[int, Field(title='Version')]
    waiting: Annotated[bool, Field(title='Waiting')]


class ProjectView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    repository: RepositoryView
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    updated_by: Annotated[UUID, Field(title='Updated By')]


class ProviderKeyView(BaseModel):
    """
    What the tenant sees of a key: its reference, who added it and when,
    its state, and when it was last used. Never its value.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    last_used_at: Annotated[AwareDatetime | None, Field(title='Last Used At')]
    provider: ProviderName
    status: KeyStatus


class ResultRequest(BaseModel):
    """
    How an item ended: the JSON of an exec result, in base64.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    crossing: CrossingBody
    data: Annotated[str, Field(max_length=16000000, title='Data')]


class RoleFillView(BaseModel):
    fallbacks: Annotated[list[FillView], Field(title='Fallbacks')]
    fill: FillView
    role: Annotated[str, Field(title='Role')]


class SessionStandingView(BaseModel):
    """
    Why a session is or is not moving. `changed_at` is its last change:
    when it parked, for a parked one. `pool_id` null is the cloud, where
    `hosts_online` is null; `share_set` false is the default share.
    """
    changed_at: Annotated[AwareDatetime, Field(title='Changed At')]
    concurrency: Annotated[int, Field(title='Concurrency')]
    hosts_online: Annotated[int | None, Field(title='Hosts Online')]
    loop: LoopStandingView | None
    own_lane: Annotated[bool, Field(title='Own Lane')]
    park: ParkView | None
    pending_input: Annotated[bool, Field(title='Pending Input')]
    plan_tier: Annotated[str, Field(title='Plan Tier')]
    pool_id: Annotated[UUID | None, Field(title='Pool Id')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    share_set: Annotated[bool, Field(title='Share Set')]
    status: SessionStatus


class StageRequest(BaseModel):
    """
    A new version of the matrix: the model roles it serves and its rows,
    one a key. It is checked whole when it is published.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    roles: Annotated[list[Role2], Field(max_length=64, min_length=1, title='Roles')]
    rows: Annotated[list[MatrixRowBody], Field(max_length=500, min_length=1, title='Rows')]


class StepShapeView(BaseModel):
    """
    One step as an operator's `read` sees it: what it is, who wrote it,
    and the fields of its header a reader acts on, never what it says.
    `content` says whether what it says is kept.
    """
    actor: Actor
    command: ControlCommand | None
    content: ContentState
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    failure: ToolFailure | None
    id: Annotated[UUID, Field(title='Id')]
    loop_id: Annotated[UUID, Field(title='Loop Id')]
    origin: Origin
    outcome: LoopOutcome | None
    park: ParkView | None
    responds_to: Annotated[UUID | None, Field(title='Responds To')]
    seq: Annotated[int, Field(title='Seq')]
    tool: Annotated[str | None, Field(title='Tool')]
    type: StepType


class StepView(BaseModel):
    """
    One step of a session's history, in its order. `text` is what it
    says: a message's words, a model's answer, a tool's result. The rest is
    its header's, by type: the tools a model response called and why it
    stopped, a tool call's tool and the class of its failure, a control's
    command, a park, a loop's outcome.
    """
    actor: Actor
    command: ControlCommand | None
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    failure: ToolFailure | None
    id: Annotated[UUID, Field(title='Id')]
    loop_id: Annotated[UUID, Field(title='Loop Id')]
    origin: Origin
    outcome: LoopOutcome | None
    park: ParkView | None
    refs: Annotated[list[UUID], Field(title='Refs')]
    responds_to: Annotated[UUID | None, Field(title='Responds To')]
    seq: Annotated[int, Field(title='Seq')]
    stop_reason: StopReason | None
    text: Annotated[str, Field(title='Text')]
    tool: Annotated[str | None, Field(title='Tool')]
    tools: Annotated[list[str], Field(title='Tools')]
    type: StepType


class ToolPolicyRequest(BaseModel):
    """
    The tenant's whole layer, written over the version `If-Match` names.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    approvers: Annotated[list[ApproverRuleBody] | None, Field(max_length=200, title='Approvers')] = None
    rules: Annotated[list[PolicyRuleBody] | None, Field(max_length=200, title='Rules')] = None


class ToolPolicyView(BaseModel):
    """
    The tenant's layer; version 1 and empty until its first write.
    """
    approvers: Annotated[list[ApproverRuleView], Field(title='Approvers')]
    rules: Annotated[list[PolicyRuleView], Field(title='Rules')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    updated_by: Annotated[UUID, Field(title='Updated By')]
    version: Annotated[int, Field(title='Version')]


class TriggerBody(BaseModel):
    """
    An event that passes every filter set (one left empty matches any),
    or a schedule, every `every` seconds, a minute at least.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    arrivals: Annotated[list[str] | None, Field(max_length=50, title='Arrivals')] = None
    effects: Annotated[list[str] | None, Field(max_length=50, title='Effects')] = None
    every: Annotated[timedelta | None, Field(title='Every')] = None
    integrations: Annotated[list[str] | None, Field(max_length=50, title='Integrations')] = None
    kind: TriggerKind


class UserPageView(BaseModel):
    """
    One page of the tenant's members. `next_cursor` fetches the next page
    and is null on the last one, so a client reads every member instead of
    whatever a fixed limit happened to cover.
    """
    items: Annotated[list[UserView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ApiKeyPageView(BaseModel):
    """
    One page of the api key list, newest first; `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[ApiKeyView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class AutomationRequest(BaseModel):
    """
    An automation whole, as made or as edited.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    action: ActionBody
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    limits: LimitsBody
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    own_events: Annotated[bool | None, Field(title='Own Events')] = False
    runs_as: RunsAs | None = None
    trigger: TriggerBody


class ChooseRequest(BaseModel):
    """
    The fill a tenant chooses for a model role: one of that role's
    options.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    fill: FillBody


class ContenderView(BaseModel):
    """
    What an arm's sessions ran: the agent kind, its version, and each model
    role's fill.
    """
    fills: Annotated[list[RoleFillView], Field(title='Fills')]
    kind: Annotated[str, Field(title='Kind')]
    kind_version: Annotated[int, Field(title='Kind Version')]


class ErrorBody(BaseModel):
    code: Annotated[str, Field(title='Code')]
    last_owner: LastOwnerDetail | None = None
    message: Annotated[str, Field(title='Message')]
    request_id: Annotated[UUID, Field(title='Request Id')]
    stream: StreamTruncatedDetail | None = None


class ErrorResponse(BaseModel):
    error: ErrorBody


class FillChoiceView(BaseModel):
    """
    The tenant's choice for one model role, from its next session on.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    fill: FillView
    id: Annotated[UUID, Field(title='Id')]
    role: Annotated[str, Field(title='Role')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    updated_by: Annotated[UUID, Field(title='Updated By')]


class FillOptionsView(BaseModel):
    """
    What a tenant on its own keys may choose for one model role: the fills
    the published matrix qualified for it, from a provider it holds a live
    key for.
    """
    fills: Annotated[list[FillView], Field(title='Fills')]
    role: Annotated[str, Field(title='Role')]


class HostStandingView(BaseModel):
    """
    Why a host takes no work: its state, what it advertised, the version
    of `exec` work it reads against the floor, when it last called, and what
    is ready on its pool's lane and its own.
    """
    advertisement: AdvertisementView
    exec_floor: Annotated[int, Field(title='Exec Floor')]
    exec_version: Annotated[int, Field(title='Exec Version')]
    host_id: Annotated[UUID, Field(title='Host Id')]
    lanes: Annotated[list[LaneLoadView], Field(title='Lanes')]
    last_seen_at: Annotated[AwareDatetime, Field(title='Last Seen At')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    revoked: Annotated[bool, Field(title='Revoked')]
    state: HostState


class InvitationPageView(BaseModel):
    """
    One page of the org's pending invitations, newest first; `next_cursor`
    as on `UserPageView`.
    """
    items: Annotated[list[InvitationView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class IssuedLoginView(BaseModel):
    """
    Carries the freshly minted login credential in the clear, once.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    memberships: Annotated[list[MembershipChoiceView], Field(title='Memberships')]
    token: Annotated[str, Field(title='Token')]


class LivePageView(BaseModel):
    session_id: Annotated[UUID, Field(title='Session Id')]
    streams: Annotated[list[LiveStreamView], Field(title='Streams')]


class MembershipChoicePageView(BaseModel):
    """
    One page of the signed-in person's places, each the org, the user, and
    the role: the same choice a sign-in answers with. `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[MembershipChoiceView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class MembershipPageView(BaseModel):
    """
    One page of the tenant's memberships, by user id; `next_cursor` as on
    `UserPageView`. A page read with the same limit as a page of users
    covers the same members, so roles pair with members page for page.
    """
    items: Annotated[list[MembershipView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ShapePageView(BaseModel):
    """
    One page of a session's shape, after the seq the request named.
    """
    has_more: Annotated[bool, Field(title='Has More')]
    items: Annotated[list[StepShapeView], Field(title='Items')]


class StepPageView(BaseModel):
    """
    One page of a session's history, after the seq the request named.
    With `has_more`, the next page starts after the last step's seq.
    """
    has_more: Annotated[bool, Field(title='Has More')]
    items: Annotated[list[StepView], Field(title='Items')]


class BenchmarkSummaryView(BaseModel):
    """
    One run of a scenario, without its trials: a point of the scenario's
    trend.
    """
    baseline: ContenderView
    baseline_result: ArmResultView
    candidate: ContenderView
    candidate_result: ArmResultView
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    id: Annotated[UUID, Field(title='Id')]
    recorded_by: Annotated[UUID, Field(title='Recorded By')]
    regressed: Annotated[bool, Field(title='Regressed')]
    scenario: Annotated[str, Field(title='Scenario')]


class BenchmarkView(BaseModel):
    """
    One run of a scenario, with every trial of both arms.
    """
    baseline: ContenderView
    baseline_result: ArmResultView
    candidate: ContenderView
    candidate_result: ArmResultView
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    id: Annotated[UUID, Field(title='Id')]
    recorded_by: Annotated[UUID, Field(title='Recorded By')]
    regressed: Annotated[bool, Field(title='Regressed')]
    scenario: Annotated[str, Field(title='Scenario')]
    trials: Annotated[list[TrialView], Field(title='Trials')]
