# generated by datamodel-codegen:
#   filename:  openapi.json

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AccountDeletedView(BaseModel):
    """
    The account is gone: `deleted_at` is when. The database's backups
    still hold it until they expire, seven days on. `provider_logout_url` is
    where the browser goes next, as on a sign-out; null when the sign-in
    left no session there.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None


class Actor(StrEnum):
    """
    Who produced a step.
    """
    person = 'person'
    program = 'program'
    agent = 'agent'
    model = 'model'
    engine = 'engine'
    external = 'external'


class TtlDays(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=90, title='Ttl Days')]


class Capability(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9_.-]{0,62}$')]


class CaseTallyBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failed: Annotated[int | None, Field(ge=0, title='Failed')] = 0
    passed: Annotated[int | None, Field(ge=0, title='Passed')] = 0
    skipped: Annotated[int | None, Field(ge=0, title='Skipped')] = 0


class ClaimRequest(BaseModel):
    """
    The version of `exec` work the host reads, and nothing else: what it
    is handed is its identity's to say.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    exec_version: Annotated[int, Field(ge=1, title='Exec Version')]


class ClaimedStationWorkView(BaseModel):
    """
    One item a daemon was handed, as `station` work of `wire_version`.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    id: Annotated[UUID, Field(title='Id')]
    kind: Annotated[str, Field(title='Kind')]
    lease_expires_at: Annotated[AwareDatetime | None, Field(title='Lease Expires At')]
    payload: Annotated[dict[str, Any], Field(title='Payload')]
    target_id: Annotated[UUID, Field(title='Target Id')]
    wire_version: Annotated[int, Field(title='Wire Version')]


class ClaimedWorkView(BaseModel):
    """
    One item a host was handed, under a lease, as `exec` work of
    `wire_version`. `payload` is the item's, as its kind fixes it.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    id: Annotated[UUID, Field(title='Id')]
    kind: Annotated[str, Field(title='Kind')]
    lease_expires_at: Annotated[AwareDatetime | None, Field(title='Lease Expires At')]
    payload: Annotated[dict[str, Any], Field(title='Payload')]
    target_id: Annotated[UUID, Field(title='Target Id')]
    wire_version: Annotated[int, Field(title='Wire Version')]


class CommandBody(BaseModel):
    """
    One operation for the station's adapter, with its parameters: data,
    never code.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: Annotated[str, Field(pattern='^[a-z][a-z0-9_.-]{0,99}$', title='Operation')]
    parameters: Annotated[dict[str, Any] | None, Field(title='Parameters')] = None


class CommandPartView(BaseModel):
    seq: Annotated[int, Field(title='Seq')]
    stream: Annotated[str, Field(title='Stream')]
    text: Annotated[str, Field(title='Text')]


class ArgvItem(RootModel[str]):
    root: Annotated[str, Field(max_length=4096, min_length=1)]


class CommandRequest(BaseModel):
    """
    A command by hand: what it runs, where in the workspace, and how long
    it may take. Its key is the request's idempotency key.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: Annotated[list[ArgvItem], Field(max_length=256, min_length=1, title='Argv')]
    cwd: Annotated[str | None, Field(max_length=4096, min_length=1, title='Cwd')] = '.'
    timeout_seconds: Annotated[int | None, Field(gt=0, le=3600, title='Timeout Seconds')] = 300


class CommandView(BaseModel):
    operation: Annotated[str, Field(title='Operation')]
    parameters: Annotated[dict[str, Any], Field(title='Parameters')]


class ConfirmTotpRequest(BaseModel):
    """
    The first code from the authenticator, which confirms the secret.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class ControlCommand(StrEnum):
    """
    What a `control` step records: a command that travels out of band.
    """
    pause = 'pause'
    resume = 'resume'
    cancel = 'cancel'
    interrupt = 'interrupt'
    compact = 'compact'
    approve = 'approve'
    deny = 'deny'
    unlock = 'unlock'


class ControlKind(StrEnum):
    """
    What one line of a host's control stream says.
    """
    wake = 'wake'
    ping = 'ping'
    cancel = 'cancel'
    interrupt = 'interrupt'
    deadline = 'deadline'
    revoke = 'revoke'


class RequestSeq(RootModel[int]):
    root: Annotated[int, Field(ge=1, title='Request Seq')]


class ControlView(BaseModel):
    """
    One line of a host's control stream. `wake` asks it to claim now,
    `ping` keeps the stream open, and the rest end the item named at once.
    """
    id: Annotated[UUID | None, Field(title='Id')] = None
    item_id: Annotated[UUID | None, Field(title='Item Id')] = None
    kind: ControlKind


class CreateLabRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]


class CreateOrgRequest(BaseModel):
    """
    An org with its owner, as `bootstrap` seeds one. The owner's identity
    is created with its personal org when the email is new; the owner signs
    in through the identity provider with the address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    owner_email: Annotated[str, Field(min_length=1, title='Owner Email')]
    owner_name: Annotated[str, Field(max_length=200, min_length=1, title='Owner Name')]
    slug: Annotated[str, Field(max_length=100, min_length=1, title='Slug')]


class Label(RootModel[str]):
    root: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,62}$')]


class CreatePoolRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    labels: Annotated[list[Label] | None, Field(max_length=32, title='Labels')] = None
    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]
    region: Annotated[str, Field(pattern='^[a-z][a-z0-9-]{0,31}$', title='Region')]


class CreateStationPoolRequest(BaseModel):
    """
    `job_seconds` is the declared length of one holding, which a place's
    estimate reads.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    job_seconds: Annotated[int | None, Field(ge=1, le=604800, title='Job Seconds')] = 600
    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]


class CreateStationRequest(BaseModel):
    """
    A station of a lab, in a pool. `hold_seconds` is how long a lease
    outlives a job while its session is parked. No limit of the station's
    travels here: they are its owner's, on its host.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: Annotated[list[Capability] | None, Field(max_length=32, title='Capabilities')] = None
    hold_seconds: Annotated[int | None, Field(ge=1, le=86400, title='Hold Seconds')] = 300
    lab_id: Annotated[UUID, Field(title='Lab Id')]
    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]


class Slug(RootModel[str]):
    root: Annotated[str, Field(max_length=48, min_length=1, title='Slug')]


class CreateTeamOrgRequest(BaseModel):
    """
    A team org the caller makes and owns. `slug` is lower-case letters and
    digits joined by hyphens; left out, one is made from the name. A taken
    slug is 409.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    slug: Annotated[Slug | None, Field(title='Slug')] = None


class CredentialKind(StrEnum):
    api_key = 'api_key'
    session_token = 'session_token'
    login = 'login'
    socket_ticket = 'socket_ticket'
    operator_token = 'operator_token'
    internal = 'internal'


class CrossingKind(StrEnum):
    enrollment = 'enrollment'
    claim = 'claim'
    stream_part = 'stream_part'
    artifact = 'artifact'
    result = 'result'


class DecisionRequest(BaseModel):
    """
    A person's decision on the tool call at a seq. A denial's note is what
    the model reads.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    approve: Annotated[bool, Field(title='Approve')]
    note: Annotated[str | None, Field(max_length=100000, title='Note')] = ''


class ReturnTo(RootModel[str]):
    root: Annotated[str, Field(max_length=2000, min_length=1, title='Return To')]


class DeleteAccountRequest(BaseModel):
    """
    The account's email as the person typed it, which is how they say
    they mean it; and, as on the sign-out, where the identity provider sends
    the browser once it has ended its own session.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=1, title='Email')]
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class DeleteOrgRequest(BaseModel):
    """
    The org's name as its owner typed it, which is how they say they mean
    it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]


class DeliveryReceivedView(BaseModel):
    """
    The delivery checked out and is queued; the provider stops retrying.
    """
    received: Annotated[bool, Field(title='Received')]


class DevSignInRequest(BaseModel):
    """
    Local and test only: a sign-in by address alone, with no browser round
    trip, for the seed, the traffic generator, and the tests. A
    person nobody knew is made, with their personal org. A deployed
    environment never serves it: the route answers 404 there, and the
    process refuses to start with it on.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str | None, Field(max_length=200, title='Display Name')] = ''
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]


class DeviceSignInView(BaseModel):
    """
    The start of a sign-in for a device with no browser, the command
    line. The person opens `verification_uri_complete` (or
    `verification_uri` and types `user_code`) in any browser; the device
    keeps `device_code` to itself and asks `POST /v1/auth/device/token`
    with it every `interval` seconds, for at most `expires_in` seconds.
    """
    device_code: Annotated[str, Field(title='Device Code')]
    expires_in: Annotated[int, Field(title='Expires In')]
    interval: Annotated[int, Field(title='Interval')]
    user_code: Annotated[str, Field(title='User Code')]
    verification_uri: Annotated[str, Field(title='Verification Uri')]
    verification_uri_complete: Annotated[str, Field(title='Verification Uri Complete')]


class DeviceTokenRequest(BaseModel):
    """
    The device code a device sign-in started with. The answer is a
    sign-in's once the person confirmed it; before that, 400
    `sign_in_pending` (or `sign_in_slow_down`: ask less often), and 401
    `sign_in_refused` when they declined or it expired.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    device_code: Annotated[str, Field(max_length=500, min_length=1, title='Device Code')]


class EnrollmentTokenView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class EventView(BaseModel):
    """
    One record of the tenant's append-only stream, paged by `after_seq`.
    `kind` is "<namespace>.<entity>.<action>", or an audit kind; the payload
    stays inside, an event is a record and not a second read path.
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class ExchangeSessionRequest(BaseModel):
    """
    The org to enter. Presented with the sign-in credential, it opens the
    first session; presented with a session, it is a switch, and that session
    ends in the same write.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: Annotated[UUID, Field(title='Org Id')]


class ExecDetailView(BaseModel):
    """
    An item the host holds: the call, the workspace, and the operation.
    """
    call_id: Annotated[UUID, Field(title='Call Id')]
    deadline: Annotated[AwareDatetime, Field(title='Deadline')]
    effect: Annotated[str, Field(title='Effect')]
    epoch: Annotated[int | None, Field(title='Epoch')]
    item_id: Annotated[UUID, Field(title='Item Id')]
    location: Annotated[str, Field(title='Location')]
    org_id: Annotated[UUID, Field(title='Org Id')]
    request: Annotated[dict[str, Any], Field(title='Request')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    spec: Annotated[dict[str, Any], Field(title='Spec')]


class ExecLeaseView(BaseModel):
    lease_expires_at: Annotated[AwareDatetime, Field(title='Lease Expires At')]


class ExecState(StrEnum):
    queued = 'queued'
    running = 'running'
    done = 'done'
    interrupted = 'interrupted'


class FilePurpose(StrEnum):
    """
    Which context a file came from. The purpose decides the bounds an
    upload is held to and what `subject_id` names. A product adds a purpose
    per kind of file it keeps, with its bounds (`media.rules.BOUNDS`).
    """
    upload = 'upload'


class FileStatus(StrEnum):
    pending = 'pending'
    stored = 'stored'


class FileView(BaseModel):
    """
    A file the tenant keeps: its name, type, and size, never its bytes and
    never where they live. `status` is `pending` until the upload is
    confirmed, then `stored`.
    """
    content_type: Annotated[str, Field(title='Content Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    extension: Annotated[str, Field(title='Extension')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]
    status: FileStatus
    subject_id: Annotated[UUID | None, Field(title='Subject Id')]


class GiveBackRequest(BaseModel):
    """
    What the person did, as the agent reads it on resume.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    summary: Annotated[str, Field(max_length=100000, min_length=1, title='Summary')]


class HandRunView(BaseModel):
    """
    A command by hand as recorded: the item that holds what ran, the
    person it is attributed to, and the writer epoch it runs under.
    """
    command_key: Annotated[UUID, Field(title='Command Key')]
    epoch: Annotated[int, Field(title='Epoch')]
    item_id: Annotated[UUID, Field(title='Item Id')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    state: ExecState
    user_id: Annotated[UUID, Field(title='User Id')]


class InvitationState(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    revoked = 'revoked'


class IsolationMode(StrEnum):
    """
    The isolation levels a host can run a workspace at, strongest first.
    """
    vm = 'vm'
    container = 'container'
    directory = 'directory'


class IssuedDaemonCredentialView(BaseModel):
    """
    The lab daemon's credential in the clear, once: it lives a day, for
    its owner to install it, and the daemon rotates it from then on.
    """
    credential_id: Annotated[UUID, Field(title='Credential Id')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    lab_id: Annotated[UUID, Field(title='Lab Id')]
    token: Annotated[str | None, Field(title='Token')]


class IssuedDownloadView(BaseModel):
    """
    A link to the file's bytes that works until `expires_at`. A null `url`
    means the store cannot sign one: the bytes come from
    `GET /v1/media/files/{id}/content`.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    url: Annotated[str | None, Field(title='Url')]


class IssuedEnrollmentTokenView(BaseModel):
    """
    The token in the clear, once: it enrolls hosts into its pool until
    it expires or is revoked. It is minted on every call, so a retry mints
    another, and the one never read expires on its own.
    """
    enrollment: EnrollmentTokenView
    token: Annotated[str | None, Field(title='Token')]


class IssuedHostCredentialView(BaseModel):
    """
    The host's own credential in the clear, once, and the identity it
    carries. It lives an hour; the host rotates it before then.
    """
    credential_id: Annotated[UUID, Field(title='Credential Id')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    host_id: Annotated[UUID, Field(title='Host Id')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    token: Annotated[str | None, Field(title='Token')]


class IssuedTicketView(BaseModel):
    """
    Carries the freshly minted socket ticket in the clear, once; redeeming
    it opens the channel and re-checks the credential behind it.
    """
    expires_in_seconds: Annotated[int, Field(title='Expires In Seconds')]
    ticket: Annotated[str, Field(title='Ticket')]


class IssuedTotpSecretView(BaseModel):
    """
    A freshly minted TOTP secret, once, as the `otpauth://` URI an
    authenticator app reads. A replay carries none.
    """
    otpauth_uri: Annotated[str | None, Field(title='Otpauth Uri')]


class Abort(RootModel[str]):
    root: Annotated[str, Field(max_length=500, min_length=1, title='Abort')]


class JoinLineRequest(BaseModel):
    """
    A session's ask: one station of the pool, or any that serves, with
    the capabilities it needs; and what it binds, the candidate under test,
    the procedure, and its version.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate: Annotated[str, Field(pattern='^\\S{1,200}$', title='Candidate')]
    capabilities: Annotated[list[Capability] | None, Field(max_length=32, title='Capabilities')] = None
    procedure: Annotated[str, Field(pattern='^[a-z][a-z0-9_.-]{0,99}$', title='Procedure')]
    procedure_version: Annotated[str, Field(pattern='^\\S{1,200}$', title='Procedure Version')]
    project: Annotated[str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9_./-]{0,199}$', title='Project')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    station_id: Annotated[UUID | None, Field(title='Station Id')] = None


class LabView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]


class LeaseTimeView(BaseModel):
    fencing_token: Annotated[int, Field(title='Fencing Token')]
    lease_id: Annotated[UUID, Field(title='Lease Id')]
    seconds: Annotated[float, Field(title='Seconds')]


class LeaseView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    ended: Annotated[str | None, Field(title='Ended')]
    ended_at: Annotated[AwareDatetime | None, Field(title='Ended At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    fencing_token: Annotated[int, Field(title='Fencing Token')]
    id: Annotated[UUID, Field(title='Id')]
    lab_id: Annotated[UUID, Field(title='Lab Id')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    station_id: Annotated[UUID, Field(title='Station Id')]


class LeftLinesView(BaseModel):
    left: Annotated[int, Field(title='Left')]
    session_id: Annotated[UUID, Field(title='Session Id')]


class LineEntryView(BaseModel):
    candidate: Annotated[str, Field(title='Candidate')]
    capabilities: Annotated[list[str], Field(title='Capabilities')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    id: Annotated[UUID, Field(title='Id')]
    lease_id: Annotated[UUID | None, Field(title='Lease Id')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    procedure: Annotated[str, Field(title='Procedure')]
    procedure_version: Annotated[str, Field(title='Procedure Version')]
    project: Annotated[str, Field(title='Project')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    state: Annotated[str, Field(title='State')]
    station_id: Annotated[UUID | None, Field(title='Station Id')]


class LinePlaceView(BaseModel):
    """
    An entry, how many wait ahead of it, and the estimate of its wait.
    """
    entry: LineEntryView
    estimate_seconds: Annotated[int, Field(title='Estimate Seconds')]
    position: Annotated[int, Field(title='Position')]


class LiveReadView(BaseModel):
    """
    A handle to one session's open streams until `expires_at`. Read it
    at `GET /v1/live?handle=`; a viewer asks for a new one when it ends.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    handle: Annotated[str, Field(title='Handle')]
    session_id: Annotated[UUID, Field(title='Session Id')]


class LogoutRequest(BaseModel):
    """
    Where the identity provider sends the browser once it has ended its own
    session: this environment's portal page for it, and nothing else. Left
    out, the provider sends it to its default sign-out address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    return_to: Annotated[ReturnTo | None, Field(title='Return To')] = None


class LoopOutcome(StrEnum):
    """
    The five ways a loop ends. A park is none of them.
    """
    succeeded = 'succeeded'
    failed = 'failed'
    inconclusive = 'inconclusive'
    cancelled = 'cancelled'
    errored = 'errored'


class MessageRequest(BaseModel):
    """
    A message to the session, said in the caller's name. It wakes an idle
    session, and a running loop reads it at its next model request.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Annotated[str, Field(max_length=100000, min_length=1, title='Text')]


class ExpiresIn(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=3600, title='Expires In')]


class OperatorEventView(BaseModel):
    """
    The same record as an operator reads it, with the two provenance fields
    a tenant's own feed leaves out: the request that produced it and the app
    it came from, which is what a support investigation correlates on.
    """
    actor_id: Annotated[UUID, Field(title='Actor Id')]
    app: Annotated[str, Field(title='App')]
    kind: Annotated[str, Field(title='Kind')]
    produced_at: Annotated[AwareDatetime, Field(title='Produced At')]
    request_id: Annotated[UUID, Field(title='Request Id')]
    seq: Annotated[int, Field(title='Seq')]
    target_id: Annotated[UUID, Field(title='Target Id')]


class OperatorRole(StrEnum):
    """
    What an allowlist entry lets an operator do across every tenant. Write
    includes read; the tenancy namespace's table says which permissions each
    role holds, as it does for `Role`.
    """
    read = 'read'
    write = 'write'


class OperatorTokenView(BaseModel):
    """
    One operator token as its operator reads it: never the secret, which is
    kept as its digest. `revoked_at` is set once it was ended.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class OperatorView(BaseModel):
    """
    Who the operator plane admitted: the identity and what its allowlist
    entry grants, so a skill checks it holds the entry it expects before it
    reads anything.
    """
    email: Annotated[str, Field(title='Email')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]
    operator_role: OperatorRole


class OrgKind(StrEnum):
    """
    What an org is for. Every person has exactly one personal org, made
    with them; every other org is a team org, made on purpose.
    """
    personal = 'personal'
    team = 'team'


class OrgView(BaseModel):
    """
    `kind` says what the org is for: every person has one `personal` org,
    made with them, which is never deleted and never changes hands; every
    other org is a `team` org.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')] = None
    id: Annotated[UUID, Field(title='Id')]
    kind: OrgKind
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class Origin(StrEnum):
    """
    Where a step came in.
    """
    portal = 'portal'
    cli = 'cli'
    api = 'api'
    integration = 'integration'
    automation = 'automation'
    parent = 'parent'
    engine = 'engine'


class OutputStream(StrEnum):
    stdout = 'stdout'
    stderr = 'stderr'


class OwnedOrgRef(BaseModel):
    """
    An org named in a refusal: enough to find it and to say which.
    """
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    slug: Annotated[str, Field(title='Slug')]


class ParkReason(StrEnum):
    """
    Why a loop waits, and so what clears it.
    """
    person = 'person'
    provider = 'provider'
    budget = 'budget'
    resource = 'resource'
    job = 'job'
    children = 'children'
    handover = 'handover'
    pause = 'pause'


class ParkView(BaseModel):
    """
    Why a parked loop waits, what clears it, and when it tries again by
    itself; a park only a person clears has no time.
    """
    reason: ParkReason
    retry_at: Annotated[AwareDatetime | None, Field(title='Retry At')]
    unlock: Annotated[str, Field(title='Unlock')]


class PartKind(StrEnum):
    text = 'text'
    thinking = 'thinking'
    tool_input = 'tool_input'
    tool_output = 'tool_output'


class Permission(StrEnum):
    read = 'read'
    write = 'write'
    manage_members = 'manage_members'
    manage_keys = 'manage_keys'


class PlaceSessionRequest(BaseModel):
    """
    One of the tenant's pools, or None for the cloud.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    pool_id: Annotated[UUID | None, Field(title='Pool Id')]


class PlatformSizeView(BaseModel):
    """
    How big the platform is, what the first responder to an alarm reads
    before it escalates: live tenants and users, and the events produced in
    the twenty-four hours from `since` to `counted_at`. The maintenance
    worker counts it every few minutes, and this is its latest count:
    `counted_at` says how old the answer is.
    """
    counted_at: Annotated[AwareDatetime, Field(title='Counted At')]
    events_last_24h: Annotated[int, Field(title='Events Last 24H')]
    since: Annotated[AwareDatetime, Field(title='Since')]
    tenants: Annotated[int, Field(title='Tenants')]
    users: Annotated[int, Field(title='Users')]


class PoolView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    labels: Annotated[list[str], Field(title='Labels')]
    name: Annotated[str, Field(title='Name')]
    region: Annotated[str, Field(title='Region')]


class Provenance(StrEnum):
    """
    From the strongest to the weakest.
    """
    real = 'real'
    twin = 'twin'
    double = 'double'
    unavailable = 'unavailable'


class PurposeUsageView(BaseModel):
    count: Annotated[int, Field(title='Count')]
    pending_count: Annotated[int, Field(title='Pending Count')]
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purpose: FilePurpose
    size_bytes: Annotated[int, Field(title='Size Bytes')]


class RefusalReason(StrEnum):
    """
    Why the daemon did not run a command.
    """
    fenced = 'fenced'
    limit = 'limit'
    unknown_operation = 'unknown_operation'
    lease_ended = 'lease_ended'


class ReorderRequest(BaseModel):
    """
    The waiting entry this one goes ahead of, or null for the end.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    before: Annotated[UUID | None, Field(title='Before')]


class RevokedDaemonView(BaseModel):
    credentials_ended: Annotated[int, Field(title='Credentials Ended')]
    lab_id: Annotated[UUID, Field(title='Lab Id')]


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'
    viewer = 'viewer'
    service = 'service'


class RunOutcome(StrEnum):
    passed = 'passed'
    failed = 'failed'
    errored = 'errored'
    aborted = 'aborted'


class SecondFactorRequest(BaseModel):
    """
    The code from an authenticator, presented with a sign-in credential.
    The answer is a new sign-in that records the verified code, which the
    operator plane asks of an enrolled operator. A code used once is
    refused.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    totp_code: Annotated[str, Field(max_length=6, min_length=6, title='Totp Code')]


class SessionControl(StrEnum):
    """
    The controls a person sends a session out of band. A decision on one
    tool call is a route of its own.
    """
    pause = 'pause'
    resume = 'resume'
    cancel = 'cancel'
    interrupt = 'interrupt'
    compact = 'compact'
    unlock = 'unlock'


class SessionStatus(StrEnum):
    pending = 'pending'
    running = 'running'
    parked = 'parked'
    idle = 'idle'


class SessionView(BaseModel):
    """
    Only the hash of a token is ever kept, so a session view carries no secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class InvitationToken(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Invitation Token')]


class SignInCallbackRequest(BaseModel):
    """
    The code the browser brought back to the callback, and the verifier
    the sign-in's start answered with, which the API exchanges with the
    identity provider, server-side. The answer is a
    sign-in's (`IssuedLoginView`); a person nobody knew is signed up by it,
    with their personal org.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=500, min_length=1, title='Code')]
    code_verifier: Annotated[str, Field(max_length=128, min_length=43, title='Code Verifier')]
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None


class SignInStartRequest(BaseModel):
    """
    The start of a sign-in at the identity provider. `redirect_uri` is where
    the browser comes back with a code: this environment's portal callback,
    and nothing else. `state` is the caller's own random value, kept by the
    tab that started the sign-in and compared when the browser comes back,
    which binds the round trip to that tab; it may carry nothing else.
    `invitation_token` is the one an invitation's link carried, and
    `sign_up` opens the provider on its sign-up screen.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    invitation_token: Annotated[InvitationToken | None, Field(title='Invitation Token')] = None
    redirect_uri: Annotated[str, Field(max_length=2000, min_length=1, title='Redirect Uri')]
    sign_up: Annotated[bool | None, Field(title='Sign Up')] = False
    state: Annotated[str, Field(max_length=200, min_length=16, title='State')]


class SignInStartView(BaseModel):
    """
    Where the browser goes next, the identity provider's sign-in, and the
    PKCE verifier the tab keeps beside its state and sends back with the
    code. The provider holds only the verifier's digest, so a code is worth
    nothing to anyone who does not hold it.
    """
    authorization_url: Annotated[str, Field(title='Authorization Url')]
    code_verifier: Annotated[str, Field(title='Code Verifier')]


class SignedOutView(BaseModel):
    """
    The credential that ended, a session, a sign-in, or an operator
    token, and `provider_logout_url`: where the browser goes next to end the
    identity provider's session behind it, so the next sign-in on this
    browser asks who it is. Null when the sign-in left no session there
    (the device sign-in, the local sign-in, an operator token). It names the
    provider's session, which is not a secret.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    credential_kind: CredentialKind
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    provider_logout_url: Annotated[str | None, Field(title='Provider Logout Url')] = None
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class Intent(StrEnum):
    sso = 'sso'
    domain_verification = 'domain_verification'


class SsoLinkRequest(BaseModel):
    """
    What the identity provider's admin portal opens on: the single sign-on
    connection (`sso`) or the org's domains (`domain_verification`), and the
    page of this environment's portal it links back to.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    intent: Annotated[Intent, Field(title='Intent')]
    return_url: Annotated[str, Field(max_length=2000, min_length=1, title='Return Url')]


class SsoLinkView(BaseModel):
    """
    A short-lived link to the admin portal; open it at once.
    """
    url: Annotated[str, Field(title='Url')]


class StartSessionRequest(BaseModel):
    """
    A session to start on the latest version of a kind the product runs.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Annotated[str, Field(max_length=200, min_length=1, title='Kind')]
    title: Annotated[str, Field(max_length=200, min_length=1, title='Title')]


class StartUploadRequest(BaseModel):
    """
    An upload to start: the file's name as the uploader had it, its type,
    and its size in bytes. The type must be one the purpose accepts and match
    the name's extension; the size is the most the store will take.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    content_type: Annotated[str, Field(max_length=255, min_length=1, title='Content Type')]
    name: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    size_bytes: Annotated[int, Field(gt=0, title='Size Bytes')]


class StationClaimRequest(BaseModel):
    """
    The version of `station` work the daemon reads, and nothing else:
    what it is handed is its identity's to say.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    station_version: Annotated[int, Field(ge=1, title='Station Version')]


class StationJobView(BaseModel):
    """
    A job under a lease: its station and token are the lease's, and what
    it runs the lease's ask bound.
    """
    candidate: Annotated[str, Field(title='Candidate')]
    commands: Annotated[list[CommandView], Field(title='Commands')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    fencing_token: Annotated[int, Field(title='Fencing Token')]
    finished_at: Annotated[AwareDatetime | None, Field(title='Finished At')]
    id: Annotated[UUID, Field(title='Id')]
    lab_id: Annotated[UUID, Field(title='Lab Id')]
    lease_id: Annotated[UUID, Field(title='Lease Id')]
    procedure: Annotated[str, Field(title='Procedure')]
    procedure_version: Annotated[str, Field(title='Procedure Version')]
    project: Annotated[str, Field(title='Project')]
    run_id: Annotated[UUID | None, Field(title='Run Id')]
    session_id: Annotated[UUID, Field(title='Session Id')]
    state: Annotated[str, Field(title='State')]
    station_id: Annotated[UUID, Field(title='Station Id')]


class StationPoolView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    job_seconds: Annotated[int, Field(title='Job Seconds')]
    name: Annotated[str, Field(title='Name')]


class StationView(BaseModel):
    """
    A station, with the highest fencing token granted on it and the
    lease that holds it, while one does.
    """
    capabilities: Annotated[list[str], Field(title='Capabilities')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    fencing_token: Annotated[int, Field(title='Fencing Token')]
    held_until: Annotated[AwareDatetime | None, Field(title='Held Until')]
    hold_seconds: Annotated[int, Field(title='Hold Seconds')]
    id: Annotated[UUID, Field(title='Id')]
    lab_id: Annotated[UUID, Field(title='Lab Id')]
    lease_id: Annotated[UUID | None, Field(title='Lease Id')]
    name: Annotated[str, Field(title='Name')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]


class StepType(StrEnum):
    """
    What a step records. The type answers questions, so no caller
    compares strings.
    """
    message = 'message'
    event = 'event'
    control = 'control'
    model_request = 'model_request'
    model_response = 'model_response'
    tool_request = 'tool_request'
    tool_response = 'tool_response'
    summary = 'summary'
    parked = 'parked'
    resumed = 'resumed'
    loop_ended = 'loop_ended'
    switched = 'switched'
    environment_changed = 'environment_changed'


class StopKind(StrEnum):
    """
    What the control stream tells a host about one item it holds. Each
    ends the command at once.
    """
    cancel = 'cancel'
    interrupt = 'interrupt'
    deadline = 'deadline'
    revoke = 'revoke'


class StopReason(StrEnum):
    """
    Why a response stopped. A model's refusal is a response its agent kind
    handles, never a provider error.
    """
    end_turn = 'end_turn'
    tool_use = 'tool_use'
    output_limit = 'output_limit'
    refusal = 'refusal'
    content_filter = 'content_filter'
    pause = 'pause'


class StorageUsageView(BaseModel):
    """
    What the org keeps in the store, counted from its files: the stored ones
    per purpose and in total, and the uploads started and not yet confirmed.
    A removed file stops counting at once.
    """
    pending_size_bytes: Annotated[int, Field(title='Pending Size Bytes')]
    purposes: Annotated[list[PurposeUsageView], Field(title='Purposes')]
    total_count: Annotated[int, Field(title='Total Count')]
    total_size_bytes: Annotated[int, Field(title='Total Size Bytes')]


class StreamTruncatedDetail(BaseModel):
    """
    What a `stream_truncated` refusal carries: the floor, the highest seq
    trimmed from the stream, and the head. A client drops its cursor, reads
    afresh what it shows, and goes on from the head.
    """
    floor: Annotated[int, Field(title='Floor')]
    head: Annotated[int, Field(title='Head')]


class SubmitJobRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    commands: Annotated[list[CommandBody], Field(max_length=100, min_length=1, title='Commands')]


class ToolFailure(StrEnum):
    """
    The class of a tool failure, decided where the failure happens. The
    model reads it with advice on what to do next.
    """
    invalid_input = 'invalid_input'
    transient = 'transient'
    timeout = 'timeout'
    denied = 'denied'
    interrupted = 'interrupted'
    permanent = 'permanent'


class TotpConfirmedView(BaseModel):
    """
    The second factor is enrolled: from now on the operator plane admits
    this identity only on a sign-in that verified a code, so the next
    request signs in again with one.
    """
    confirmed_at: Annotated[AwareDatetime, Field(title='Confirmed At')]
    identity_id: Annotated[UUID, Field(title='Identity Id')]


class UpdateIdentityRequest(BaseModel):
    """
    Where the person is, as an IANA name ("Europe/Istanbul"): the portal
    sends the browser's own on sign-in, and a time shown or sent to the
    person is in it; with none sent, in UTC. A name that is not one is
    422.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    time_zone: Annotated[str, Field(max_length=64, min_length=1, title='Time Zone')]


class UpdateMeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]


class UpdateMembershipRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Role


class UploadFieldView(BaseModel):
    name: Annotated[str, Field(title='Name')]
    value: Annotated[str, Field(title='Value')]


class UserView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    display_name: Annotated[str, Field(title='Display Name')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class WorkKind(StrEnum):
    NOOP = 'NOOP'
    ORCHESTRATION = 'ORCHESTRATION'
    WAKE_PARKED = 'WAKE_PARKED'
    DELETE_ACCOUNT = 'DELETE_ACCOUNT'
    DELETE_ORG = 'DELETE_ORG'
    WAKE_SESSION = 'WAKE_SESSION'
    WAKE_SESSIONS = 'WAKE_SESSIONS'
    LOOP = 'LOOP'
    EXEC = 'EXEC'
    WORKSPACE = 'WORKSPACE'
    STATION = 'STATION'


class WorkStatus(StrEnum):
    queued = 'queued'
    claimed = 'claimed'
    done = 'done'
    failed = 'failed'


class AddApiKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    role: Role
    ttl_days: Annotated[TtlDays | None, Field(title='Ttl Days')] = None


class AddMemberRequest(BaseModel):
    """
    A person in the org, as `add-member` seeds one; the owner and the
    service role are refused, since the one owner is the one the create
    minted.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    display_name: Annotated[str, Field(max_length=200, min_length=1, title='Display Name')]
    email: Annotated[str, Field(min_length=1, title='Email')]
    role: Role


class AdvertisementBody(BaseModel):
    """
    What a host probed at its startup, and nothing it did not.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: Annotated[list[Capability] | None, Field(max_length=64, title='Capabilities')] = None
    isolation_modes: Annotated[list[IsolationMode] | None, Field(max_length=3, title='Isolation Modes')] = None
    os: Annotated[str, Field(max_length=64, min_length=1, title='Os')]
    shell: Annotated[str | None, Field(max_length=64, title='Shell')] = ''


class AdvertisementView(BaseModel):
    capabilities: Annotated[list[str], Field(title='Capabilities')]
    isolation_modes: Annotated[list[IsolationMode], Field(title='Isolation Modes')]
    os: Annotated[str, Field(title='Os')]
    shell: Annotated[str, Field(title='Shell')]


class AgentSessionView(BaseModel):
    """
    A session: its kind, its title, and its status, which follows its
    steps. `pending` while an input waits for a run, `running` while a run
    holds its loop, `parked` while the loop waits, `idle` when no loop is
    open.
    """
    archived_at: Annotated[AwareDatetime | None, Field(title='Archived At')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    id: Annotated[UUID, Field(title='Id')]
    kind: Annotated[str, Field(title='Kind')]
    kind_version: Annotated[int, Field(title='Kind Version')]
    park: ParkView | None
    status: SessionStatus
    title: Annotated[str, Field(title='Title')]


class ApiKeyView(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    deleted_at: Annotated[AwareDatetime | None, Field(title='Deleted At')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    role: Role
    user_id: Annotated[UUID, Field(title='User Id')]


class ClaimView(BaseModel):
    """
    What a claim answers: the item, or none when nothing is ready.
    """
    item: ClaimedWorkView | None


class CommandProgressView(BaseModel):
    """
    How a command stands: its state, its output after the last part read,
    and how it ended once it has. `refused` names why its host or the relay
    refused it, such as a command a later run fenced.
    """
    exit_code: Annotated[int | None, Field(title='Exit Code')] = None
    parts: Annotated[list[CommandPartView], Field(title='Parts')]
    refused: Annotated[str | None, Field(title='Refused')] = None
    state: ExecState
    stderr: Annotated[str | None, Field(title='Stderr')] = None
    stdout: Annotated[str | None, Field(title='Stdout')] = None
    stopped: StopKind | None = None
    timed_out: Annotated[bool | None, Field(title='Timed Out')] = False
    truncated: Annotated[bool | None, Field(title='Truncated')] = False


class ControlRequest(BaseModel):
    """
    A control. An interrupt names the seq of the tool request it stops,
    and no other control names one.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    command: SessionControl
    request_seq: Annotated[RequestSeq | None, Field(title='Request Seq')] = None


class CrossingBody(BaseModel):
    """
    What the sender declares of the bytes it sends: what they are, their
    SHA-256 in hex, and their size.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: CrossingKind
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$', title='Sha256')]
    size: Annotated[int, Field(ge=0, title='Size')]


class EnrollRequest(BaseModel):
    """
    A host's name and its report, beside its enrollment token. The pool
    is the token's.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    advertisement: AdvertisementBody
    exec_version: Annotated[int, Field(ge=1, title='Exec Version')]
    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]


class FilePageView(BaseModel):
    """
    One page of the org's stored files, oldest first. `next_cursor` fetches
    the next page and is null on the last one.
    """
    items: Annotated[list[FileView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HeartbeatRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    advertisement: AdvertisementBody
    exec_version: Annotated[int, Field(ge=1, title='Exec Version')]


class HostView(BaseModel):
    """
    A host as its owner reads it: online while it called within the
    window and reads a version of `exec` work the platform still hands.
    """
    advertisement: AdvertisementView
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    exec_version: Annotated[int, Field(title='Exec Version')]
    id: Annotated[UUID, Field(title='Id')]
    last_seen_at: Annotated[AwareDatetime, Field(title='Last Seen At')]
    name: Annotated[str, Field(title='Name')]
    online: Annotated[bool, Field(title='Online')]
    pool_id: Annotated[UUID, Field(title='Pool Id')]
    revoked_at: Annotated[AwareDatetime | None, Field(title='Revoked At')]


class IdentityView(BaseModel):
    """
    The person behind the caller's user. `operator_role` is the allowlist
    entry: null for a person who is not an operator.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    email: Annotated[str, Field(title='Email')]
    id: Annotated[UUID, Field(title='Id')]
    operator_role: OperatorRole | None
    time_zone: Annotated[str | None, Field(title='Time Zone')] = None


class InvitationView(BaseModel):
    """
    A person asked to join the org. The identity provider sent the email
    with the link; `expires_at` is when the link stops working, after which
    the invitation is sent again or replaced.
    """
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    created_by: Annotated[UUID, Field(title='Created By')]
    email: Annotated[str, Field(title='Email')]
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    state: InvitationState


class InviteMemberRequest(BaseModel):
    """
    The address to invite and the role the person gets, at most the
    caller's own.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[str, Field(max_length=320, min_length=3, title='Email')]
    role: Role


class IssuedApiKeyView(BaseModel):
    """
    The key in the clear is present on the first response only: the stored
    outcome of the create carries no secret, so a replay under the same
    Idempotency-Key answers with `key` null and `Idempotent-Replayed: true`. A
    client that lost the first response revokes the key and issues another.
    """
    api_key: ApiKeyView
    key: Annotated[str | None, Field(title='Key')]


class IssuedOperatorTokenView(BaseModel):
    """
    The token in the clear, on this answer only; `id` names it afterwards,
    in the list and the revoke, and is no secret. The mint ends the sign-in
    it was given, so a client that lost this answer signs in again for
    another token and revokes the lost one by its id from the list.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    id: Annotated[UUID, Field(title='Id')]
    permission: OperatorRole
    token: Annotated[str | None, Field(title='Token')]


class IssuedSessionView(BaseModel):
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    org: OrgView
    role: Role
    token: Annotated[str, Field(title='Token')]
    user: UserView


class IssuedUploadView(BaseModel):
    """
    A form to post the file with, straight to the store: every field, in
    order, then the file as the last field, named `file`. The signed policy
    holds the post to the file's type and at most its size, until
    `expires_at`. A null `url` means the store cannot take a post: the bytes
    go to `PUT /v1/media/files/{id}/content` instead. Then the upload is
    confirmed.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    fields: Annotated[list[UploadFieldView], Field(title='Fields')]
    url: Annotated[str | None, Field(title='Url')]


class LastOwnerDetail(BaseModel):
    """
    What a `last_owner` refusal carries: every team org the person is the
    last owner of, which they hand on or delete before their account goes.
    """
    orgs: Annotated[list[OwnedOrgRef], Field(title='Orgs')]


class LivePartView(BaseModel):
    """
    One part of a stream: its kind, its place, and its text. `index` is
    the block of a model response it belongs to; a tool call's input names
    the call, and a tool's output its channel.
    """
    channel: Annotated[str | None, Field(title='Channel')] = None
    index: Annotated[int | None, Field(title='Index')] = None
    kind: PartKind
    n: Annotated[int, Field(title='N')]
    text: Annotated[str, Field(title='Text')]
    tool: Annotated[str | None, Field(title='Tool')] = None
    tool_use_id: Annotated[str | None, Field(title='Tool Use Id')] = None


class LiveStreamView(BaseModel):
    """
    One open stream: the step it adds up to, the oldest part the service
    still holds, the parts after the last one read, and whether parts never
    read were let go. The step holds them once it is stored.
    """
    dropped: Annotated[bool, Field(title='Dropped')]
    first: Annotated[int, Field(title='First')]
    parts: Annotated[list[LivePartView], Field(title='Parts')]
    step_id: Annotated[UUID, Field(title='Step Id')]


class MeView(BaseModel):
    app: Annotated[str, Field(title='App')]
    org: OrgView
    permissions: Annotated[list[Permission], Field(title='Permissions')]
    role: Role
    user: UserView


class MembershipChoiceView(BaseModel):
    org: OrgView
    role: Role
    user: UserView


class MembershipView(BaseModel):
    id: Annotated[UUID, Field(title='Id')]
    role: Role
    teams: Annotated[list[UUID], Field(title='Teams')]
    user_id: Annotated[UUID, Field(title='User Id')]


class MintOperatorTokenRequest(BaseModel):
    """
    One permission, never wider than the caller's entry (`write` implies
    `read`), and a lifetime of at most an hour, an hour when absent.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_in: Annotated[ExpiresIn | None, Field(title='Expires In')] = None
    permission: OperatorRole


class OperatorTokenPageView(BaseModel):
    """
    One page of the caller's live operator tokens, newest first;
    `next_cursor` as on `UserPageView`.
    """
    items: Annotated[list[OperatorTokenView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class OperatorWorkItemView(BaseModel):
    """
    One background job as an operator reads it: what it does and for
    which record, where it stands, and how many of its attempts are spent.
    The payload and the claim stay the worker's.
    """
    attempts: Annotated[int, Field(title='Attempts')]
    available_at: Annotated[AwareDatetime, Field(title='Available At')]
    id: Annotated[UUID, Field(title='Id')]
    kind: WorkKind
    last_error: Annotated[str | None, Field(title='Last Error')]
    max_attempts: Annotated[int, Field(title='Max Attempts')]
    status: WorkStatus
    target_id: Annotated[UUID, Field(title='Target Id')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class OrgDeletedView(BaseModel):
    """
    The org is gone for everyone in it: `deleted_at` is when. `session` is
    the owner's new session in their personal org, which replaces the one
    that asked, as a switch's does; null when none could be made, and the
    owner signs in again.
    """
    deleted_at: Annotated[AwareDatetime, Field(title='Deleted At')]
    session: IssuedSessionView | None = None


class OrgPageView(BaseModel):
    """
    One page of every org, by id, for the operator plane; `next_cursor` as
    on `UserPageView`.
    """
    items: Annotated[list[OrgView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class PartRequest(BaseModel):
    """
    One part of an item's output, in the order the host read it.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    crossing: CrossingBody
    data: Annotated[str, Field(max_length=90000, title='Data')]
    seq: Annotated[int, Field(ge=0, title='Seq')]
    stream: OutputStream


class PlacementView(BaseModel):
    """
    Where a session runs. A pinned session with no host of its pool
    online is `waiting`; it never moves to the cloud by itself.
    """
    hosts_online: Annotated[int, Field(title='Hosts Online')]
    pool: PoolView | None
    session_id: Annotated[UUID, Field(title='Session Id')]
    version: Annotated[int, Field(title='Version')]
    waiting: Annotated[bool, Field(title='Waiting')]


class RefusalBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: Annotated[str, Field(max_length=500, min_length=1, title='Detail')]
    operation: Annotated[str, Field(max_length=100, min_length=1, title='Operation')]
    reason: RefusalReason
    refused_at: Annotated[AwareDatetime, Field(title='Refused At')]


class ResultRequest(BaseModel):
    """
    How an item ended: the JSON of an exec result, in base64.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    crossing: CrossingBody
    data: Annotated[str, Field(max_length=16000000, title='Data')]


class StationClaimView(BaseModel):
    """
    What a claim answers: the item, the job it names, and how many
    seconds the job's lease has left, which the daemon times on its own
    monotonic clock. No item when nothing is ready; no job for an item that
    names none.
    """
    item: ClaimedStationWorkView | None
    job: StationJobView | None = None
    lease_seconds: Annotated[float | None, Field(title='Lease Seconds')] = 0


class StepView(BaseModel):
    """
    One step of a session's history, in its order. `text` is what it
    says: a message's words, a model's answer, a tool's result. The rest is
    its header's, by type: the tools a model response called and why it
    stopped, a tool call's tool and the class of its failure, a control's
    command, a park, a loop's outcome.
    """
    actor: Actor
    command: ControlCommand | None
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    failure: ToolFailure | None
    id: Annotated[UUID, Field(title='Id')]
    loop_id: Annotated[UUID, Field(title='Loop Id')]
    origin: Origin
    outcome: LoopOutcome | None
    park: ParkView | None
    refs: Annotated[list[UUID], Field(title='Refs')]
    responds_to: Annotated[UUID | None, Field(title='Responds To')]
    seq: Annotated[int, Field(title='Seq')]
    stop_reason: StopReason | None
    text: Annotated[str, Field(title='Text')]
    tool: Annotated[str | None, Field(title='Tool')]
    tools: Annotated[list[str], Field(title='Tools')]
    type: StepType


class UserPageView(BaseModel):
    """
    One page of the tenant's members. `next_cursor` fetches the next page
    and is null on the last one, so a client reads every member instead of
    whatever a fixed limit happened to cover.
    """
    items: Annotated[list[UserView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ApiKeyPageView(BaseModel):
    """
    One page of the api key list, newest first; `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[ApiKeyView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class ErrorBody(BaseModel):
    code: Annotated[str, Field(title='Code')]
    last_owner: LastOwnerDetail | None = None
    message: Annotated[str, Field(title='Message')]
    request_id: Annotated[UUID, Field(title='Request Id')]
    stream: StreamTruncatedDetail | None = None


class ErrorResponse(BaseModel):
    error: ErrorBody


class InvitationPageView(BaseModel):
    """
    One page of the org's pending invitations, newest first; `next_cursor`
    as on `UserPageView`.
    """
    items: Annotated[list[InvitationView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class IssuedLoginView(BaseModel):
    """
    Carries the freshly minted login credential in the clear, once.
    """
    expires_at: Annotated[AwareDatetime, Field(title='Expires At')]
    memberships: Annotated[list[MembershipChoiceView], Field(title='Memberships')]
    token: Annotated[str, Field(title='Token')]


class JobReportRequest(BaseModel):
    """
    What the daemon says of a job it ran. `run_id` is the daemon's, so a
    retried report lands once. A run a refusal ended is `aborted`, names
    the refusal in `abort`, and lists every refused command.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    abort: Annotated[Abort | None, Field(title='Abort')] = None
    adapter: Annotated[str, Field(max_length=200, min_length=1, title='Adapter')]
    cases: CaseTallyBody | None = None
    commands_run: Annotated[int, Field(ge=0, le=100, title='Commands Run')]
    daemon_version: Annotated[str, Field(pattern='^\\S{1,200}$', title='Daemon Version')]
    finished_at: Annotated[AwareDatetime, Field(title='Finished At')]
    outcome: RunOutcome
    provenance: Provenance
    refused: Annotated[list[RefusalBody] | None, Field(max_length=100, title='Refused')] = None
    run_id: Annotated[UUID, Field(title='Run Id')]
    started_at: Annotated[AwareDatetime, Field(title='Started At')]


class LivePageView(BaseModel):
    session_id: Annotated[UUID, Field(title='Session Id')]
    streams: Annotated[list[LiveStreamView], Field(title='Streams')]


class MembershipChoicePageView(BaseModel):
    """
    One page of the signed-in person's places, each the org, the user, and
    the role: the same choice a sign-in answers with. `next_cursor` as on
    `UserPageView`.
    """
    items: Annotated[list[MembershipChoiceView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class MembershipPageView(BaseModel):
    """
    One page of the tenant's memberships, by user id; `next_cursor` as on
    `UserPageView`. A page read with the same limit as a page of users
    covers the same members, so roles pair with members page for page.
    """
    items: Annotated[list[MembershipView], Field(title='Items')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')]


class StepPageView(BaseModel):
    """
    One page of a session's history, after the seq the request named.
    With `has_more`, the next page starts after the last step's seq.
    """
    has_more: Annotated[bool, Field(title='Has More')]
    items: Annotated[list[StepView], Field(title='Items')]
