"""The lens catalog as agentic-check knows it: every lens id and its severity.

A rule names a lens by id, and its severity is the lens's. The review
skills read the lens files; an installed checker has no lens files, so
it carries this table, and the set of lenses whose rule is `core`.
The engine's `tests/test_agentic_check.py` holds both equal to its
`lenses/*.md` and its spec: a lens added, removed, re-rated, or
re-cited there is changed here in the same change.
"""

from __future__ import annotations

from acme.agentic_check.model import Severity

LENSES: dict[str, Severity] = {
    "STP-01": "medium",
    "STP-02": "medium",
    "STP-03": "medium",
    "STP-04": "medium",
    "STP-05": "medium",
    "STP-06": "medium",
    "STP-07": "medium",
    "STP-08": "medium",
    "STP-09": "medium",
    "STP-10": "high",
    "STP-11": "high",
    "STP-12": "high",
    "STP-13": "medium",
    "STP-14": "medium",
    "WIN-01": "medium",
    "WIN-02": "medium",
    "WIN-03": "medium",
    "WIN-04": "medium",
    "WIN-05": "high",
    "WIN-06": "medium",
    "WIN-07": "medium",
    "WIN-08": "medium",
    "MOD-01": "medium",
    "MOD-02": "high",
    "MOD-03": "medium",
    "MOD-04": "medium",
    "MOD-05": "medium",
    "MOD-06": "medium",
    "MOD-07": "medium",
    "MOD-08": "medium",
    "TOL-01": "medium",
    "TOL-02": "high",
    "TOL-03": "high",
    "TOL-04": "high",
    "TOL-05": "medium",
    "TOL-06": "high",
    "TOL-07": "high",
    "TOL-08": "medium",
    "TOL-09": "medium",
    "TOL-10": "medium",
    "TOL-11": "high",
    "TOL-12": "high",
    "TOL-13": "high",
    "TOL-14": "high",
    "LIV-01": "medium",
    "LIV-02": "medium",
    "LIV-03": "medium",
    "LIV-04": "medium",
    "LIV-05": "medium",
    "LIV-06": "medium",
    "TRU-01": "medium",
    "TRU-02": "medium",
    "TRU-03": "high",
    "TRU-04": "medium",
    "TRU-05": "high",
    "TRU-06": "high",
    "TRU-07": "medium",
    "TRU-08": "medium",
    "AGT-01": "medium",
    "AGT-02": "medium",
    "AGT-03": "medium",
    "AGT-04": "high",
    "AGT-05": "medium",
    "AGT-06": "high",
    "AGT-07": "high",
    "BND-01": "medium",
    "BND-02": "high",
    "BND-03": "high",
    "BND-04": "high",
    "BND-05": "medium",
    "BND-06": "medium",
    "BND-07": "medium",
    "BND-08": "medium",
    "BND-09": "medium",
    "BND-10": "medium",
    "PRV-01": "medium",
    "PRV-02": "medium",
    "PRV-03": "medium",
    "PRV-04": "medium",
    "PRV-05": "medium",
    "PRV-06": "medium",
    "PRV-07": "medium",
    "PRV-08": "high",
    "PRV-09": "medium",
}

CORE: frozenset[str] = frozenset(
    {
        "BND-02",
        "BND-03",
        "BND-04",
        "BND-09",
        "BND-10",
        "MOD-01",
        "PRV-01",
        "PRV-02",
        "STP-01",
        "STP-02",
        "STP-03",
        "STP-07",
        "STP-08",
        "STP-09",
        "STP-10",
        "STP-11",
        "STP-12",
        "STP-13",
        "STP-14",
        "TOL-01",
        "TOL-02",
        "TOL-06",
        "TOL-11",
        "TOL-12",
        "TOL-13",
        "TOL-14",
        "TRU-01",
        "TRU-02",
        "TRU-03",
        "TRU-04",
        "TRU-05",
    }
)
"""The lenses whose first Source, the section that states the rule, is tagged
`core` in the spec. A departure from such a rule is a different engine,
never a deviation, so no disable or exception may name one."""
